### ISSUE TITLE
Restrict alphabetical sorting to My Items

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4463] opened 2021-11-15 22:54 UTC
**Is your feature request related to a problem? Please describe.**
Alphabetical sorting [was recently added to the tree](https://github.com/nasa/openmct/pull/4376), but we should tweak this so that [it only applies to the My Items folder and its children](https://github.com/nasa/openmct/issues/1717#issuecomment-941250163). Applying alphabetical sorting universally takes control of sorting away from the plugin provider.

Testing Instructions
1. See that `My Items` (or any of its various aliases) and children of `My Items` is sorted alphabetically
2. See that dictionaries and children of dictionaries are NOT sorted alphabetically*
3. See that dictionaries appear before `My Items` in object tree (I think)

\* dictionaries may be sorted alphabetically... but not by Open MCT

**Comment by michaelrogers** [comment] 2021-11-16 14:08
Relates to issue #1717

**Comment by michaelrogers** [comment] 2021-11-16 20:22
@akhenry - I may need some assistance clarifying the intent of this issue. 

On initial inspection, this ascending sort seems to only affect the myItems or `key='mine'` directories. The logic added to check for that key appears to be functioning as expected, but I wanted to confirm that applying the sort to all descendants of myItems is the intended functionality. The current implementation will recursively sort every directory nested beneath myItems.

**Comment by davetsay** [comment] 2021-11-17 05:40
@michaelrogers , the issue is that `const sortedComposition = composition.sort(this.sortNameDescending);` is actually still sorting composition, because `sort` sorts in place. I'm pushing a fix in for #4464 so I can close this with the same PR.

**Comment by davetsay** [comment] 2021-11-17 07:24
> @michaelrogers , the issue is that `const sortedComposition = composition.sort(this.sortNameDescending);` is actually still sorting composition, because `sort` sorts in place. I'm pushing a fix in for #4464 so I can close this with the same PR.

Um. Scratch that @michaelrogers . Should not even execute that line if the check is working. Carry on then.

**Comment by michaelrogers** [comment] 2021-11-17 14:23
No worries, thanks for looking into it @davetsay. Let me know if you want to coordinate on the two fixes.

**Comment by michaelrogers** [comment] 2021-11-17 20:55
Just wanted to circle back, I've recreated a dictionary plugin that is populated in the tree locally. The alphabetic sorting appears to only sort those objects nested beneath myItems / identifier.key = 'mine'.

**Comment by akhenry** [comment] 2021-11-22 18:57
What's the status of this issue? The associated PR seems to have been closed?

**Comment by michaelrogers** [comment] 2021-11-22 19:05
The short answer is for this specific issue, I have confirmed that alphabetization is limited to MyItems. This was done by introducing example plugins that created directories and also with example dictionaries. One thing to note, there was no functional change to scoping the sort, I believe it is working as intended. 

There are a few issues that are closely related this feature that surfaced during the last testathon:
* https://github.com/nasa/openmct/issues/4483 
* A regression of the functionality that resorted the tree after a new object is inserted - I am coordinating with Dave on that one.

**Closed** 2022-01-03 23:49 UTC
Labels: type:bug, severity:critical
