### ISSUE TITLE
[Plot options] improve Plot options layout in Inspector

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#2068] opened 2018-06-12 21:01 UTC
Vertical alignment is messed up and rows need more space.

**Comment by psarram** [comment] 2018-06-12 21:03
![a608c350-4c6b-11e8-8ad4-34431c10ef69](https://user-images.githubusercontent.com/26494733/41317195-5a2afaca-6e49-11e8-839f-f226ab6d4676.png)

**Comment by charlesh88** [comment] 2018-06-13 16:22
Closing, this is a dupe of #2011

**Closed by charlesh88** 2018-06-13 16:22 UTC
