### ISSUE TITLE
[locator widget] unclear what is happening when folders are not valid selections 

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1008] opened 2016-06-09 23:40 UTC
When a user is using the locator widget (e.g. move, copy, link, etc), and they select a location that is invalid, the locator refreshes with no contents selected.

With scratchpad enabled, you can reproduce like so:

1. Create a folder inside of the "scratchpad" folder.
2. Create an object inside of the "my items" folder.
3. right click on the object you created in "my items" and select "move".
4. in the locator widget, expand the scratchpad folder.
5. Select the folder you created in the "scratchpad" folder as the destination.

Behavior: the locator tree collapses, the folder you attempted to select is no longer visible.  There is no message indicating why it doesn't work.

Here's a short gif showing current behavior:
![clicking-is-weird](https://cloud.githubusercontent.com/assets/226503/15950095/af37aa7a-2e60-11e6-90c2-867de8f86a5b.gif)

Throwing this in le guin for triage, we can move it to a later sprint after looking at it.

@charlesh88 think we'd need some design about how to show users that their selection is invalid.  Or should we grey out invalid choices?  Need some messaging to users about why this can't be done.

**Comment by charlesh88** [comment] 2016-06-09 23:45
What is scratchpad? Why is this action invalid? I made what looks like a folder in a folder, why can't I move my thing to it? Why is the tree collapsing? Is this a case of "that object can't contain the object I'm trying to move"?

**Comment by larkin** [comment] 2016-06-09 23:52
Short story: The object can't contain the object you are trying to move.  The behavior when that happens is rather odd.  This is one way to reproduce that behavior.  Other methods may exist.

**Comment by charlesh88** [comment] 2016-06-09 23:53
Ok, but why is "Scratch Folder" collapsing? I would think you can't select it and the Ok button doesn't hilite, but it stays expanded.

**Comment by larkin** [comment] 2016-06-09 23:58
@charlesh88 Another reproduction:
1. create a folder
2. right click on folder, select "move."
3. in the locator, select the folder you are moving as the destination.

You'll get the same behavior as mentioned above-- the tree collapses and your selection is not made.

**Comment by larkin** [comment] 2016-06-10 00:03
"You can't select it and the ok button doesn't highlight but it stays expanded" 
That would be better than the current behavior.  It's not saying "this is invalid," it's saying "this doesn't work."  Would be nice to clearly tell the user, "this is invalid" or even better "this is invalid for x reason".

I'm happy to split this into a short term fix and a long term improvement-- your call.  Ultimately, I was planning to push this to Le Guin.

**Comment by charlesh88** [comment] 2016-06-10 00:12
So, just tried creating a folder and Moving it into itself, and in fact, anything other than a folder. The current behavior, pardon my french, is fucked. Any click on a thing that can't contain the thing I'm moving collapses the entire tree up to My Items, no matter how much time I spent climbing down the tree. This is wrong, wrong, wrong. 

The fix should be as I describe: you can't select the intended target and the Ok button doesn't hilite, but leave the tree expansion state as is. If we could gray out items that aren't valid targets, that'd be cool.

I'm sure this wasn't deliberate - it's probably a emergent behavior of our system. Or, Angular JS is becoming self-aware, and we're headed for a unpleasant and undesirable Singularity excursion. I don't think this is a burning priority; let's take a look in Le Guin.

**Comment by larkin** [comment] 2016-06-10 00:13
Le Guin it is!

**Comment by charlesh88** [comment] 2016-06-10 00:14
Also, agree on desire to tell the user why they can't do the action they are trying.

**Comment by VWoeltjen** [comment] 2016-06-10 22:24
Jotting some notes here after investigating #1007 (which exhibited some behaviors that seem similar to this issue, for which a fix was unnecessary; we just needed to remove an obsolete policy to make the selection valid)

Currently, there's a Locator-uses-TreeView relationship. That much is fine. But the locator is where the validation gets handled (via a passed-in validation function), and that's where we run into problems: The locator recognizes that a selection is invalid, then "fixes" it by restoring the last valid selection.

There's a watch from `mct-tree` for the selection which is not firing as expected when this occurs, which is why we saw some of the [specific behavior](https://github.com/nasa/openmct/issues/1007#issuecomment-225238671) in #1007, and also may be the root cause here.

Understanding why this doesn't fire would be nice, but we should probably address this more deeply anyway. Graying out unselectable tree items would be much easier if the TreeView itself allowed a validation function to be passed in - and this issue might just disappear if we did handle it that way. TreeView takes on some more responsibility, but it's a reasonable one: It's a control for selecting things and supporting validation is consistent with that. The Locator, then, becomes a much more trivial wrapper around this control (primarily there for styling purposes) and could probably be refactored down to a simple template.

**Comment by larkin** [comment] 2016-06-10 23:11
Alternative to a `verify` function being passed to tree view: what if the tree view defines a factory function that it uses for generating child nodes views (similar, perhaps, to how you would register a View with our new API) which we can override when we want to control the appearance of child nodes?  It could be used to apply special styling (grey it out), filter nodes, or anything else we may need.

**Comment by charlesh88** [comment] 2016-06-22 01:00
Reassign this next sprint.

**Comment by larkin** [comment] 2016-07-26 18:13
From Tag-up 2016-07-26:  can run into this relatively easily, if we can resolve this or minimize the bad behavior that would be great, e.g. don't collapse entire tree on invalid selection.

If we have time this sprint we will address.

**Comment by VWoeltjen** [comment] 2016-07-26 23:03
Looking at this again today, trying to Create a Folder and save it in a Layout, which should be prohibited.

Instead of collapsing, I'm able to select the Layout (even though it's invalid), but when I click OK, the newly-created Folder gets saved somewhere else (whatever the last valid value selected in the tree was).

Not sure why the characteristics of this issue have changed, but still suspect that some watch we expect to be firing isn't.

**Comment by charlesh88** [comment] 2016-07-26 23:05
When this thing gains self-awareness, I don't think it's going to be happy and that we're all going to be in trouble.

**Comment by VWoeltjen** [comment] 2016-07-28 19:53
#1100 addresses the regression (as it currently manifests), such that invalid destinations cannot be selected in the Locator. It does not include any changes to appearance (e.g. greying out non-selectable destinations); filed #1102 for these, but have left in the backlog.

> When this thing gains self-awareness, I don't think it's going to be happy and that we're all going to be in trouble.

I think we'll be okay, unless we got priority order wrong on the three laws. Be careful turning it off.

**Comment by charlesh88** [comment] 2016-08-05 23:33
Woot! Glad to hear this has been fixed.

**Comment by charlesh88** [comment] 2016-08-08 22:02
Testathon 08-08-2016: verified fixed.

**Comment by larkin** [comment] 2016-08-08 22:28
Verified fixed.

**Comment by Costigan** [comment] 2016-08-08 23:25
I can't verify it's fixed.  I just replicated the misbehavior (8/8/2016).  I searched for mshirley with 'Folder' checked.  That found my folder under My Items.  I selected that in the tree.  I saw its contents.  I created a new folder called 'test folder' underneath My Items>mshirley>.  I right clicked on it and selected 'move'.  I browsed to select 'test folder' as the location to move it to.  The tree in the location dialog closed up just as described in the bug report.  I then deleted 'test folder' successfully, thinking I was done, and I noticed the two bubbles visible here:
![testfolderbug](https://cloud.githubusercontent.com/assets/8198486/17499801/b22941b4-5d84-11e6-9552-c9d36e7407cd.png)

**Comment by Costigan** [comment] 2016-08-08 23:26
I'm running Version 0.11.1-SNAPSHOT, Built 2016-08-08T18:24:11Z, which is at the link for this testathon.

**Comment by akhenry** [comment] 2016-08-10 20:12
Reopening because seeing the behavior above.

**Comment by larkin** [comment] 2016-08-10 20:15
Can easily reproduce by trying to move an object into it self or into it's parent.

**Comment by VWoeltjen** [comment] 2016-08-10 20:17
Seeing this from Move dialog and not Create dialog. Not sure why fix for Create did not also fix in the context of Move, needs investigation. See console errors from #1114 at the same time, may or may not be related.

**Comment by VWoeltjen** [comment] 2016-08-15 23:17
Looking into this a little bit, jotting down some notes:

* Think #1114 is unrelated, will have a related PR in for that shortly. (Problem occurs even if #1114 is solved.)
* `mct-tree`'s `link` function gets invoked twice when this occurs. I think that means the `mct-tree` element is getting recreated (or at least recompiled/relinked) for some reason that I do not yet know. Think issue may be in Locator (controller or template, most likely) rather than tree itself, based on this
* Only seems to be reproducible when the selection state is restored to an initial `undefined` value. After selecting something in the locator for Move, am unable to reproduce this issue.
* I'd been suspicious of exceptions, esp. because we see some garbage info bubbles left behind in some cases.
  * I think we have a bug where Info bubbles display for objects in a locator (they shouldn't), but display behind the Move dialog (so we don't notice/care so much). Guessing that the weird leftover bubbles are ones that were spawned from an `mct-tree` element that got replaced (for reasons that I still don't understand)

**Closed** 2016-08-28 16:29 UTC
Labels: bug, regression, unverified

**Comment by charlesh88** [comment] 2016-08-29 22:03
Testathon 2016-08-29: verified fixed via a variety of "tries":

- Move/Dupe an object into itself.
- Move/Dupe an object into a container that can't contain it (Activity Type into Layout, Panel, etc.)
- Create an object and save it into something that can't contain it.

In all cases, I was not able to hilite the incorrect destination, and the the tree did not collapse.
