### ISSUE TITLE
[UI][Search] Search bar overlap

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#2095] opened 2018-07-02 20:53 UTC
Search bar seems to have a minimum width, which causes it to overlap the splitter when the tree is adjusted.

![image](https://user-images.githubusercontent.com/13260688/42185848-4f2366f6-7dff-11e8-91c4-291a57cf5a73.png)

**Comment by charlesh88** [comment] 2018-07-02 21:48
Closing as a dupe of #2094.

**Closed by charlesh88** 2018-07-02 21:48 UTC
