### ISSUE TITLE
[Conditionals] In edit mode, last active style is applied instead of selected style

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2950] opened 2020-04-16 23:15 UTC
eg.
![Screen Shot 2020-04-16 at 4 14 53 PM](https://user-images.githubusercontent.com/4215777/79515434-797e5f80-7ffd-11ea-9d89-5dc590d5846a.png)

Steps to reproduce:
1. Create a condition widget
2. Select a condition set 
3. Define some conditional styling
4. Select a style to be applied, observe that it correctly applies the selected style.
4. Save, and exit edit mode
5. Observe dynamic styling taking place
6. When a style OTHER THAN the previously selected style is active, enter edit mode
7. Observe that the last dynamic style is still applied, rather than the currently selected style.

**Comment by shefalijoshi** [comment] 2021-09-28 21:44
Duplicate of #4196

**Closed by shefalijoshi** 2021-09-28 21:44 UTC
