### ISSUE TITLE
[Create] 404 Errors on all object create events.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#378] opened 2015-12-05 00:14 UTC
This is caused by issue #377

In PersistenceCapability.persist() the model's .persisted attribute is [set using the mutationCapability](https://github.com/nasa/openmctweb/blob/master/platform/core/src/capabilities/PersistenceCapability.js#L138). This triggers a listener in the GenericSearchProvider which attempts to fetch the as yet unpersisted model from the persistence store.

This issue does not affect user experience, so should not block user testing, but will result in error log filled with 404 errors, especially on copy.

Ticketing this as a separate issue to #377 so it can be fixed in isolation if need be.

**Comment by VWoeltjen** [comment] 2015-12-08 19:14
From tag-up 12/8/2015 - think search should be using a different event (e.g. a persistence topic?). Unsaved changes shouldn't be searchable anyway, so the fact that we're indexing based on unsaved changes necessarily leaves room for bugs like this.

**Comment by VWoeltjen** [comment] 2016-05-31 19:55
Can't reproduce, believe this was addressed by #727

**Closed by VWoeltjen** 2016-05-31 19:55 UTC

**Comment by VWoeltjen** [comment] 2016-05-31 22:03
Verified fixed testathon 20160531
