### ISSUE TITLE
Save when creating a new object should also allow Save and Continue

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2085] opened 2018-06-21 17:39 UTC
When creating a new object, the only Save option is "Save As..." which, once the user has gone through the Save dialog, exits from editing. There should also be a "Save and Continue" option which would return the user to their object (in Edit mode) after the Save dialog.

**Comment by larkin** [comment] 2018-06-28 21:33
There's a regression here, it used to be a dropdown option for the save as button which gave "save and continue".

**Comment by larkin** [comment] 2018-06-28 21:36
Actually, this is a dupe of https://github.com/nasa/openmct/issues/1181.  Going to close as dupe, please refer to #1181.

**Closed by larkin** 2018-06-28 21:36 UTC
