### ISSUE TITLE
In the Live Demo, Time Conductor appears randomly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#897] opened 2016-05-06 18:03 UTC
Some objects display the Time Conductor (Mars Weather Display Layout), and some don't (Edit Display Layout Example). Is there a rationale here? All time-aware objects should display the TC.

**Comment by akhenry** [comment] 2016-05-06 18:08
By design. Time conductor will only be visible in a layout that contains historical telemetry. The presence of the time conductor will actually prevent any real-time plots from working.

**Comment by akhenry** [comment] 2016-05-11 15:55
@charlesh88 Can I close this issue?

**Closed** 2016-05-11 17:19 UTC
