### ISSUE TITLE
Shared Items disappeared

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5441] opened 2022-07-06 19:23 UTC
During testathon, creating a new folder in the Shared Items (mine) folder wiped out all the other items in that folder.
NOTE: There needs to be some specific condition for this to happen - slow connectivity to couchdb/banner perhaps? We don't know the specifics.

#### Expected vs Current Behavior
New folder should have been added to Shared Items while retaining the older contents of shared items

#### Steps to Reproduce
1. Create a new folder on the Shared Items folder (on banner)
2. Observe that all the other folders have been orphaned (still exist in couchdb, but are not part of the Shared items composition)

#### Environment

* Open MCT Version: release/2.0.5
* Deployment Type: VIPER Testathon
* OS: All
* Browser: All

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
There was some slowness in reaching the banner environment, including couchdb during this testing.

**Comment by shefalijoshi** [comment] 2022-07-08 22:34
Got into this state by first going to banner/stable and then immediately switching to banner/testathon.
`request
[CouchObjectProvider.js:208](webpack://openmct/src/plugins/persistence/couch/CouchObjectProvider.js?9318)
#bulkGet
[CouchObjectProvider.js:379](webpack://openmct/src/plugins/persistence/couch/CouchObjectProvider.js?9318)
#deferBatchedGet/<
[CouchObjectProvider.js:335](webpack://openmct/src/plugins/persistence/couch/CouchObjectProvider.js?9318)
(Async: promise callback) #deferBatchedGet
[CouchObjectProvider.js:323](webpack://openmct/src/plugins/persistence/couch/CouchObjectProvider.js?9318)
get
[CouchObjectProvider.js:307](webpack://openmct/src/plugins/persistence/couch/CouchObjectProvider.js?9318)
get
[ObjectAPI.js:219](webpack://openmct/src/api/objects/ObjectAPI.js?99d1)
getOriginalPath
[ObjectAPI.js:616](webpack://openmct/src/api/objects/ObjectAPI.js?99d1)
updateSelection
[Location.vue:147](webpack://openmct/src/ui/inspector/Location.vue?4f0e)
emit
[index.js:137](webpack://openmct/node_modules/eventemitter3/index.js?4c3f)
__WEBPACK_AMD_DEFINE_RESULT__</Selection.prototype.handleSingleSelect
[Selection.js:99](webpack://openmct/src/selection/Selection.js?d770)
__WEBPACK_AMD_DEFINE_RESULT__</Selection.prototype.select
[Selection.js:73](webpack://openmct/src/selection/Selection.js?d770)
__WEBPACK_AMD_DEFINE_RESULT__</Selection.prototype.selectCapture
[Selection.js:211](webpack://openmct/src/selection/Selection.js?d770)
__WEBPACK_AMD_DEFINE_RESULT__</Selection.prototype.selectable
[Selection.js:254](webpack://openmct/src/selection/Selection.js?d770)
updateView
[ObjectView.vue:261](webpack://openmct/src/ui/components/ObjectView.vue?62bb)
show
[ObjectView.vue:303](webpack://openmct/src/ui/components/ObjectView.vue?62bb)
viewObject
[Browse.js:41](webpack://openmct/src/ui/router/Browse.js?bb5e)
navigateToPath/<
[Browse.js:95](webpack://openmct/src/ui/router/Browse.js?bb5e)`

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/5247066/178078357-2778685c-c0aa-49fa-be35-d0849d857718.png">

**Comment by charlesh88** [comment] 2022-07-11 18:09
Testathon 07-10-22: cannot reproduce, verified fixed.

**Comment by rukmini-bose** [comment] 2022-07-11 18:23
Verified Fixed Testathon 7/11/2022

**Comment by davetsay** [comment] 2022-10-19 20:16
Part of this fix was inadvertently removed due to 90662ce4a77f31774c39289e85cdf36285843e5e. Originally fixed in #5474.

**Comment by davetsay** [comment] 2022-10-21 18:35
Re-opened by mistake.

**Closed by davetsay** 2022-10-21 18:35 UTC
Labels: type:bug, severity:blocker, Target:2.0.6
