### ISSUE TITLE
Path hovering not displaying some paths properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6809] opened 2023-07-18 18:50 UTC
#### Summary
The recent addition of the ability to show paths to objects on hover + ctrl key has some inconsistent behavior:
1. In some cases, nested elements in a layout don't show full paths on hover, but instead only show their leaf end names.
2. Dictionary-based telemetry end points consistently show a path as 'missing' when hovered on in a plot legend. Missing paths are displayed using tilde as a path separator, but should be consistent and use backslash instead.

#### Environment

* Open MCT Version:  3.0.0 SNAPSHOT
* Deployment Type:  /testathon
* OS: any
* Browser: 

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by khalidadil** [comment] 2023-07-31 21:48
tooltips are throwing a bunch of errors for the VIPER plans:
```
Error: No Provider Matched for keyString "couch-search:couch-search}"
    at ObjectAPI.get (ObjectAPI.js:223:1)
    at ObjectAPI.getOriginalPath (ObjectAPI.js:785:1)
    at ObjectAPI.getOriginalPath (ObjectAPI.js:791:1)
    at async Proxy.getObjectPath (tooltipMixins.js:44:1)
    at async Proxy.showToolTip (SwimLane.vue:139:25)
```

**Comment by akhenry** [comment] 2023-08-16 16:57
Closing in favor of https://github.com/nasa/openmct/issues/6809 which has a PR linked.

**Closed by akhenry** 2023-08-16 16:57 UTC
Labels: type:bug, severity:medium

**Comment by ozyx** [comment] 2023-08-23 23:13
Also verified as it is a dupe of #6810

**Comment by charlesh88** [comment] 2023-08-23 23:24
Verified fixed Testathon 2023-08-23.
