### ISSUE TITLE
New objects not getting added to parent object - couchdb

### ISSUE THREAD

**Issue by AdamElliott-AB** [nasa/openmct#4293] opened 2021-10-06 14:06 UTC
#### Summary
We are using couchdb for persistence. Recently started having problems creating new objects. New objects seem to be created fine at first. They can be viewed and edited, but if the page is refreshed the new object is gone. Looking at the network traffic and couchdb database revealed that new object documents are getting added to couchdb, but the parent object document is not getting updated to include the new child object. No errors were reported on the browser console or couchdb logs.

#### Troubleshooting
1. Problem persisted after using the couchdb admin tool to delete all documents except "mine" and updating "mine" to have an empty composition array.
2. Problem was resolved after fully deleting the couchdb openmct database and creating a new empty openmct database. OpenMCT created a new "mine" document when the first openmct object was added.

#### Workaround
1. export original "My Items" as json
2. delete couchdb openmct database
3. create new empty openmct database
4. In OpenMCT create new folder under "My Items" called "clone". This initializes the new openmct database.
5. Import json file into the "clone" folder
6. Move objects under the "clone/My Items" folder to be directly under the root "My Items" folder
7. Delete the "clone" folder

#### Steps to Reproduce
1. We are running multiple instances of openmct/couchdb with the same configuration and environment. The only difference is the OpenMCT views/objects that users have created. The problem was only observed on one instance. This instance had over 200 documents in couchdb which included several orphan objects after the onset of the problem.

#### Environment
The problem was observed using openmct versions 1.7.7 and 1.7.5

**Comment by AdamElliott-AB** [comment] 2021-10-06 20:04
We were using 1.7.5. We did not notice the problem until we updated to 1.7.7 We afterwards reverted to 1.7.5 but the problem was still present.

**Comment by akhenry** [comment] 2021-10-06 22:04
@AdamElliott-AB Thanks for the info. Which version of Couch are you using? 

We are not seeing exactly what you're describing in our own deployments, but [we are tracking an issue with some similarities](https://github.com/nasa/openmct/issues/4147). The issue we have observed is transient though and we haven't managed to reproduce it reliably.

**Comment by akhenry** [comment] 2021-10-06 23:50
@AdamElliott-AB Is it possible that your browser or proxy have cached 1.7.7, and that after you reverted to 1.7.5 you were actually still using 1.7.7? This can happen sometimes when switching versions. You can confirm the version by clicking on the Open MCT logo in the top right.

Also, are you seeing any errors when this problem occurs? In the network tab, in the JavaScript console, or in the UI?

**Comment by shefalijoshi** [comment] 2021-10-14 20:53
I was able to reproduce similar behavior by doing the following:
1. Create an *empty* openmct database in CouchDB
2. Right-click on My Items and choose 'Add new Folder'.
3. Click OK. You will see a persistence error:
![image](https://user-images.githubusercontent.com/5247066/137390236-75feda05-e924-42d1-bbd8-57fe0ad30153.png)
4. Notice that the Folder DOES show up in the navigation tree.
5. Import a few objects into this folder.
6. Edit these objects and save them
7. Refresh the browser
8. Boom - gone!

**Comment by shefalijoshi** [comment] 2021-11-19 22:45
This is happening because the parent composition does not get updated and saved.
The save does not happen because the persisted time stamp of the objects is > the modified timestamp of the object.  (Thus concluding that the object has not been modified on this line: https://github.com/nasa/openmct/blob/1.7.8/platform/core/src/runs/TransactingMutationListener.js#L40)

**Comment by shefalijoshi** [comment] 2021-11-30 20:24
Closing this as an environment specific problem.

**Closed by shefalijoshi** 2021-11-30 20:24 UTC
Labels: type:bug, severity:blocker, bug:regression, Target:1.8.1
