### ISSUE TITLE
Need drawing functionality from fixed position in layouts

### ISSUE THREAD

**Issue by jtrimble2100** [nasa/openmct#1977] opened 2018-04-04 19:45 UTC
I'm trying to organize a display with labels, lines, drawing elements. I can only do this in fixed position. I want to be able to do this in a layout. So I move to a fixed position display and I add images but they don't show up as images, they show up as labels. Multiple mental models is confusing. Why not do all of this in a layout?

**Comment by larkin** [comment] 2018-04-04 21:10
@jtrimble2100 thanks for the request, is a dupe of https://github.com/nasa/openmct/issues/1929.  Will track your interest there.

**Closed by larkin** 2018-04-04 21:10 UTC
