### ISSUE TITLE
Context menus available in tree during editing

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#794] opened 2016-03-25 00:03 UTC
Testathon 032416.
Context menus were displaying on the tree for all object types during editing and should not have been. May be related to #792 and #783.

**Comment by charlesh88** [comment] 2016-03-29 17:28
Short-term solution here (hiding the context menu outright) is not the desired long-term solution, in which context menu items would mutate depending on browse vs. edit context.

**Comment by charlesh88** [comment] 2016-04-18 22:18
Testathon 041816
Fantastic, context menus displayed in tree showing only "Open In New Tab" as expected. Verified resolved.

**Comment by VWoeltjen** [comment] 2016-04-18 22:36
@charlesh88 - Additionally observed (during testathon 20160418) that Start/Restart actions (in addition to Open in New Tab) are available on Timers while editing:

![screen shot 2016-04-18 at 3 27 13 pm](https://cloud.githubusercontent.com/assets/1685764/14621926/3492aefe-057b-11e6-8fdb-465b81a90928.png)

Is this desired or undesired behavior?

**Comment by charlesh88** [comment] 2016-04-18 22:43
@VWoeltjen "Start" in context menu for a timer is a bit weird, but I'd argue it's a bit weird (because you can't see its current value when it's not selected) from the tree whether you're in browse or edit mode.

**Comment by VWoeltjen** [comment] 2016-04-18 23:48
Want to diagnose root cause of actions missing in the context menu in Elements pool; if addressing the root cause would conflict with solution for #824, we should re-evaluate the extent to which we solve these (for example, maybe allow Remove in the tree so that it is available in Elements as well)

**Comment by akhenry** [comment] 2016-04-19 00:08
Root cause appears to be [a policy check](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/policies/EditContextualActionPolicy.js#L42) based on editability of the target object. Policy has a rule to disable remove (among other actions) if the navigated object is in edit mode, but the target is not. This is supposed to only affect object tree items.

The problem is that telemetry points are not editable (ie. do not get wrapped as EditableDomainObjects) [by design](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/objects/EditableDomainObjectCache.js#L86)

**Comment by RCarvalhoNASA** [comment] 2016-04-21 22:34
Still happening in edit mode of a newly created item during 2016/4/21 testathon

**Comment by akhenry** [comment] 2016-04-21 22:41
Verified fixed testathon 20160421 

In edit mode, object tree shows only "Open in New Tab". Telemetry objects in layouts show only "remove"

**Comment by VWoeltjen** [comment] 2016-04-21 22:45
@RCarvalhoNASA - May need to clear cache?

In Edit mode, currently see the following actions available in a context menu:

Action | User-created obj in Elements | Packet/point in Elements | User-created obj in tree | Packet/point in tree
---------|----|-----|----|----
Remove | Yes | Yes | No | No
Open in New Tab | __No__ | __No__ | Yes | Yes
Edit Properties | Yes | No | No | No
Start | __Yes &ast;__ | No | __Yes &ast;__ | No

&ast; Timer objects only

Bolded are cases where I am unsure if this is desired behavior - but, I don't think any of these cases are harmful (and these are out of scope for the original issue [or the regression noted in the last testathon](https://github.com/nasa/openmct/issues/794#issuecomment-211604196), in any event.)

As such I'd say verified fixed, testathon 20160421.

**Comment by charlesh88** [comment] 2016-04-21 22:47
Testathon 20160421
Verified fixed as intended.

**Closed** 2016-04-21 22:48 UTC
Labels: blocker, bug

**Comment by akhenry** [comment] 2016-04-21 22:54
@VWoeltjen Yeah, good point. There's no reason why Open in New Tab should not be available in any cases.

Start doesn't make a lot of sense in Edit Mode at all. But I can't think of a good reason to actively suppress it? Other than it suggests it might serve some useful purpose when it doesn't.
