### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Yulgana33** [nasa/openmct#1778] opened 2017-10-15 13:30 UTC
Observed while building demo displays. When a nested Layout has its frame hidden, we want to hide its own btn-bar controls (view large, etc.) But nested objects inside the layout are also having their btn-bar controls hidden as well, which we don't want.

**Comment by VWoeltjen** [comment] 2017-10-16 16:28
Mysterious verbatim dupe of #1775

**Closed by VWoeltjen** 2017-10-16 16:28 UTC
