### ISSUE TITLE
Plot legends are compressing and being clipped when the plot is small

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3981] opened 2021-06-28 17:36 UTC
Fix plots in Display Layouts to prevent top and bottom legends from being clipped: 

![image](https://user-images.githubusercontent.com/1056412/121226247-30135400-c83f-11eb-89da-f537ee549183.png)

**Comment by scottbell** [comment] 2021-09-24 09:45
Was able to reproduce, investigating now.

**Comment by scottbell** [comment] 2021-09-28 10:44
@charlesh88 Would it be appropriate to set `gl-plot-legend` `min-height` to something like `18px`?

**Comment by scottbell** [comment] 2021-09-29 08:50
Removing myself from this issue to go back to work on
https://github.com/nasa/openmct/issues/4196

**Comment by nikhilmandlik** [comment] 2021-09-29 19:30
another way to fix is remove `overflow: hidden;` from `.c-plot-legend` file 'openmct/src/styles/_legacy-plots.scss'
@charlesh88 any suggestions?
<img width="460" alt="Screen Shot 2021-09-29 at 12 24 23 PM" src="https://user-images.githubusercontent.com/1292612/135335841-647ca271-31f5-461d-b29c-6b2440359b52.png">

**Comment by charlesh88** [comment] 2021-10-07 00:09
@scottbell @nikhilmandlik You guys are both not wrong, but it's a bit more complex than that and we need a better solution than just setting min-height on the legend. There's all sorts of nested scrolling that needs cleaning up. Frankly, it's become kind of a mess over time. 

WIP in branch `fix-3981`.

**Comment by davetsay** [comment] 2021-10-08 17:17
needs testing instructions @charlesh88 . I'm not sure what the cut off is to where plot legends should legitimately be clipped or not.

![image](https://user-images.githubusercontent.com/3614296/136597126-6e5e179a-3b43-43e5-99fb-8809920f3fe9.png)
don't know if this is okay or if should show legends in this really small resolution.

**Comment by akhenry** [comment] 2022-09-19 17:36
Is this a dupe of https://github.com/nasa/openmct/issues/3858?

**Closed** 2023-02-01 22:14 UTC
Labels: type:bug, severity:critical

**Comment by charlesh88** [comment] 2023-02-02 18:55
Verified fixed Testathon 2023-02-02.

**Comment by khalidadil** [comment] 2023-02-02 19:47
Verified Fixed in Testathon on 02/02/23
