### ISSUE TITLE
`package-lock.json` sadly Git-ignored?

### ISSUE THREAD

**Issue by inad9300** [nasa/openmct#7174] opened 2023-10-25 07:25 UTC
Somebody, _sadly_, added `package-lock.json` to [`.gitignore`](https://github.com/nasa/openmct/blob/v3.1.0/.gitignore#L48):
```sh
# :(
package-lock.json
```

Since building from source and using `npm install` is the suggested way to depend on Open MCT, I believe it's particularly important to commit the lock file, making sure we all get the same dependency versions, including transitive ones.

**Comment by unlikelyzero** [comment] 2023-10-29 12:42
@inad9300 thanks for filing this! This has been identified as a dupe of https://github.com/nasa/openmct/issues/1291

If you have any particular issues, please follow up on https://github.com/nasa/openmct/issues/1291

**Closed by unlikelyzero** 2023-10-29 12:42 UTC
Labels: type:bug
