### ISSUE TITLE
[MMGIS] MMGIS plugin grabs cursor when dragging pane edges

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3953] opened 2021-06-17 18:02 UTC
When resizing either the tree or Inspector pane:

<img width="2032" alt="Screen Shot 2021-06-17 at 10 58 51 AM" src="https://user-images.githubusercontent.com/1056412/122449881-38644100-cf5b-11eb-8c2d-760dd752a927.png">

If the mouse is dragged over the MMGIS window you can no longer drag the pane to make it larger, and, the mouse is locked to the pane drag edge (even without holding the mouse down) and cannot be unlocked.

The panes should be draggable as normal in other circumstances.

**Comment by davetsay** [comment] 2021-08-17 17:57
Duplicate of #3986

**Closed by davetsay** 2021-08-17 17:57 UTC
Labels: type:bug, duplicate, severity:critical, mmgis

**Comment by jvigliotta** [comment] 2021-08-24 17:47
Verified Fixed - Testathon: 8/24/2021
