### ISSUE TITLE
Windows Alt-tab changes behavior of mouse on-click select

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2320] opened 2019-03-20 17:31 UTC
The alt key is used to change the behavior of click-drag on plots. That works fine. 

Problem is it picks up alt-tab. This is hyper annoying - users alt-tab a couple times and have no idea what behavior the mouseclick will have on the plot. 

Expected behavior: Alt changes onclick behavior from select to drag. Alt-tab doesn't affect this. 
Actual behavior: both alt and alt-tab change onclick behavior of plot.

**Comment by charlesh88** [comment] 2019-09-30 22:29
@mudinthewater Not sure exactly what's the problem here... alt should only affect plots when holding the key while deliberately dragging on the plot. Alt-tabbing to switch apps in Windows shouldn't have any subsequent effect on plot gesture behavior, and if it is, then this is a bug.

**Comment by mudinthewater** [comment] 2019-09-30 23:49
@charlesh88 Yep! It's a bug - I think I've demonstrated it to you guys before. Basically happens during presentations - I'll alt-tab back to powerpoint, then back to OpenMCT, and get the wrong behavior. It's possible it only affects Windows systems, but I'm not sure.

**Comment by Mason-Chou** [comment] 2019-10-23 21:38
@mudinthewater I'm able to reproduce the bug on Windows. From my experience, it only happens when you select another program from the Task Switcher that pops up by holding down Alt-Tab. Basically the plot still thinks you're still holding down the Alt Button as you come back to it. 

I haven't tried it on a Linux system just yet, but I believe the bug will occur if the desktop environment supports such a feature.

This bug goes away the moment you press the Alt key, so if you want to be safe, just press the Alt key in the plot before trying to do any drag gestures.

**Comment by deeptailor** [comment] 2020-07-13 19:42
tracked by #3163 - closing as dupe

**Closed by deeptailor** 2020-07-13 19:42 UTC
