### ISSUE TITLE
[New Edit Mode] NEM refactoring

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#453] opened 2016-01-05 22:17 UTC
Assess how and what needs to be done for NEM refactoring; create new issues for tasks as needed.

**Comment by akhenry** [comment] 2016-01-07 02:59
I've done some analysis of the work that needs to be done here, and I've tried to break it down into discrete steps that could be merged individually, in order to keep the deltas manageable for code reviews. 

At each step current functionality in master is at least retained (except where it's explicitly restricted in __1.__ below). This way it will be a little easier to split across sprints and opens the possibility of interim testing in testathons. Could also split up some of the work. 

The lion's share of the work will still be in a single commit (__2__ below), but I think overall it's a little more manageable this way. If this approach sounds reasonable, then I will create individual tickets for each, which will have more technical details of the refactoring needed for each.

1. [ ] 1. __Restrict context menu in elements panel in classic edit mode__
Could be applied to classic edit mode in the context of #138, then it's ready to go when NEM is implemented.

1. [ ] 2. __“Seamless” Edit Mode__
_Depends on 1_
Edit mode is initiated with a button press, as with Classic Edit Mode, but is integrated with the browse view and does not cause a route or view change. Edit is no longer an application “mode” but a per-object status.
    __a.__ Bring across necessary HTML from edit.html and edit-object.html (including toolbar, elements pool), and code from edit controller. Either bring elements from edit.html to browse, or use edit.html as the base.
    __b.__ Merge in CSS changes from prototype branch. This will be necessary for seamless edit mode to alert the user that object is being edited. Can probably all use s-status-editing instead of ‘active’ etc.
1. [ ] 3. __Drag-drop to initiate edit mode__
_Depends on 2_

1. [ ] 4. __Create triggers edit mode immediately__
_Depends on 2_
In classic edit mode, create triggers a dialog. Should instead go into seamless edit mode, with the dialog appearing when the new object is saved.
1. [ ] 5. __Auto-create new panel on drag-drop composition of telemetry object__
_Depends on 3_

1. [ ] 6. __Clicking on edit button should not launch edit mode for all object types__
Already an issue for this - https://github.com/nasa/openmctweb/issues/404. It’s actually completely separate from edit mode, but should be fixed as it will definitely become apparent in any testing of NEM. Could potentially use the prototype fix in its entirety https://github.com/nasa/openmctweb/issues/320
1. [ ] 7. __Add filter for Elements box__
The elements in the elements box in edit mode should be filterable based on a user search string. This was implemented in the NEM prototype, and the implementation can probably be brought across as is - https://github.com/nasa/openmctweb/compare/nem_prototype?expand=1#diff-a52e202c60258cf88b018203f28c9435R23

**Comment by akhenry** [comment] 2016-01-07 03:01
@charlesh88 and @VWoeltjen I'd like to get your input on whether you think this approach will work. It means merging functionality into Master in stages.

**Comment by VWoeltjen** [comment] 2016-01-07 17:56
@akhenry - This sounds like a smart approach to me - steps seem like reasonable increments, both in terms of the size of change sets, and the progressive improvement of user experience (don't see any regressions which would be introduced along the way.)

**Comment by akhenry** [comment] 2016-01-12 18:44
In light of the decision to merge the NEM prototype and do refactoring in-place, this plan will form the basis of the in-place refactoring.

**Comment by VWoeltjen** [comment] 2016-03-23 16:45
This issue is labelled critical, but based on the date the label was added (Jan 5) I believe this was because this issue blocked NEM integration (at that time.) Since we subsequently chose to merge the prototype, I'd say this label could be dropped (or we could just close this issue, since specific refactoring tasks have been itemized by #481.) @charlesh88 - what are your thoughts?

**Comment by charlesh88** [comment] 2016-03-23 16:54
@akhenry I think everything in Andrew's enumerated list has been completed? If so, would argue to close this.

**Comment by akhenry** [comment] 2016-03-23 17:10
@VWoeltjen Correct. It's somewhat redundant now. I've kept it open as this ticket, and some of its child tickets have notes that might be useful during refactoring.

I've removed label and milestone. Will close ticket when all of the refactoring tickets are closed out.

**Comment by akhenry** [comment] 2016-06-14 17:49
All refactoring issues have been addressed in separate tickets

**Closed by akhenry** 2016-06-14 17:49 UTC
Labels: refactor
