### ISSUE TITLE
[Common UI] Handle glyphs as CSS classes

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#144] opened 2015-09-24 22:53 UTC
Transition to (consistently) using CSS classes to represent icons, wherever these are used. This will make it easier to add new icons via plugins (just need to include appropriate stylesheets), gives more flexibility about what an icon would be, presents icons more semantically, and consolidates some of the specific details (instead of glyph characters being strewn about HTML/CSS/JS/JSON, glyph characters are specified in CSS and icons are referenced more symbolically by some string that can be mapped to the CSS class name.)

**Comment by larkin** [comment] 2016-07-11 17:54
@charlesh88 I believe you are/were actively working on this?  Want to move to current sprint?

**Comment by charlesh88** [comment] 2016-07-12 06:52
Yes, have been working on this as #1047, sorry for the inadvertant duping.

**Comment by charlesh88** [comment] 2016-08-10 17:56
Closing as dupe of #1047.

**Closed by charlesh88** 2016-08-10 17:56 UTC
