### ISSUE TITLE
[Refactor] Use new telemetry API from Autoflow Tabular

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1810] opened 2017-11-14 23:22 UTC
Remove usage of legacy telemetry API from the Autoflow Tabular plugin, and use new APIs instead.

**Comment by VWoeltjen** [comment] 2017-11-14 23:23
Can likely address #1800 in the context of this issue

**Comment by larkin** [comment] 2017-11-14 23:23
Merged from 1810.
> autoflow tabular doesn't support limit evaluation, due to the fact that it's using the old telemetry apis in very odd ways. In general, needs a rewrite to use new APIs.

**Comment by VWoeltjen** [comment] 2017-12-18 18:43
__Note for testing:__ This is a refactor, so goal should be to test autoflow tabular for regressions.

**Comment by larkin** [comment] 2018-03-15 23:11
Testathon 3/15/2018: dates show 
![screen shot 2018-03-15 at 4 10 33 pm](https://user-images.githubusercontent.com/226503/37495655-755834b2-286b-11e8-8fd9-808e428be8ee.png)

**Comment by akhenry** [comment] 2018-03-15 23:34
@VWoeltjen Would you mind taking a look at the date formatting, it might have been caused by changing to the new API.

**Comment by akhenry** [comment] 2018-03-16 00:04
Closing this as the formatting issue is not restricted to autoflow tabular

**Closed by akhenry** 2018-03-16 00:04 UTC
Labels: unverified
