### ISSUE TITLE
Telemetry Table should have sticky column headers

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1481] opened 2017-03-21 22:22 UTC
Telemetry table headers should be sticky, not scroll off screen.

**Comment by akhenry** [comment] 2017-03-21 22:46
Think this is a dupe of https://github.com/nasa/openmct/issues/1021?

**Comment by larkin** [comment] 2017-09-18 20:45
in a time bending paradox, #1021 is now considered a dupe of this issue.  Updated description for clarity.

**Closed** 2018-06-29 18:38 UTC
Labels: unverified

**Comment by charlesh88** [comment] 2018-07-02 18:39
### Testing Notes
Ensure that tables in a variety of scenarios (see below) do the following:
- Display persistent headers.
- Do not display a horizontal scrollbar unless columns are being clipped due to insufficient width.
- Sort columns as expected.
- Filter columns as expected.

#### Test Scenarios
1. Browse to the table view of a telemetry element that has real-time data, and observe.
1. Create a Telemetry Table, add data to it and observe.
1. Take any of the above objects and add them to a Layout. Make the frame large and small, hide the frame, and observe.

**Comment by larkin** [comment] 2018-07-02 22:31
2018-07-02: Verified fixed and OH SO NICE.

**Comment by charlesh88** [comment] 2018-07-02 22:59
Testathon 07-02-2018: verified fixed, but with new issues. See Andrew's comment and this screenshot as well:
![screen shot 2018-07-02 at 3 56 54 pm](https://user-images.githubusercontent.com/1056412/42190253-e82df558-7e10-11e8-8f53-884811ae5961.png)

**Comment by akhenry** [comment] 2018-07-02 23:29
Removing unverified label. New issues created to track issues with [horizontal scroll](https://github.com/nasa/openmct/issues/2103), and with [snapshots](#2105 ).
