### ISSUE TITLE
Clock Indicator and plots blink rapidly between different values

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6830] opened 2023-07-21 17:32 UTC
#### Summary
The clock indicator in the Status area blinks rapidly between different values (as if Local and Remote clocks are in a race condition to own the display) when the main TC is switched to Local from Remote Clock. Seen during Testathon 2023-07-20.

#### Expected vs Current Behavior
The Clock Indicator should show the current "now" in whatever TC mode (RT / Fixed) based on the selected clock (Local / Remote). 

#### Environment
  
* Open MCT Version:  3.0.0
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment] 2023-07-21 19:58
I'm unable to reproduce this. I think we should revert the change to disable the Clock Indicator from VIPER.

**Comment by rukmini-bose** [comment] 2023-07-25 17:36
Unable to reproduce this as well during Testathon 7/25/2023

**Comment by charlesh88** [comment] 2023-07-25 17:48
Testathon 2023-07-25 verified fixed.

**Comment by shefalijoshi** [comment] 2023-07-28 22:00
I'm still unable to reproduce this.

**Comment by ozyx** [comment] 2023-07-31 16:29
Also unable to reproduce

**Comment by akhenry** [comment] 2023-07-31 17:59
Unable to reproduce either. @charlesh88 I think we need detailed repro steps with specific links etc. Please create a JIRA with these additional details.

**Comment by akhenry** [comment] 2023-07-31 21:16
Closing, unable to repro. Will retest.

**Closed by akhenry** 2023-07-31 21:16 UTC
Labels: type:bug, severity:blocker, bug:regression
