### ISSUE TITLE
Timeline horizontal scroll bar loss

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#819] opened 2016-04-04 21:54 UTC
In working on the stable timeline deploy, I had to zoom way out on a timeline.  See [Issue 817](https://github.com/nasa/openmct/issues/817)
The horizontal scroll bar disappeared on the full zoom out (and having a max zoom out seems like it might need a separate issue).  Even when I zoomed back in some, the scroll bar was still gone.  It only reappeared when I got down to the original zoom level.
![timeline display bug](https://cloud.githubusercontent.com/assets/5769437/14264865/1b788530-fa75-11e5-8ac7-3e23ad17890c.jpg)

**Comment by charlesh88** [comment] 2017-09-18 19:02
@VWoeltjen Still an issue?

**Comment by VWoeltjen** [comment] 2017-09-18 22:09
Unable to reproduce; closing. May have been resolved by work for #817 et al

**Closed by VWoeltjen** 2017-09-18 22:09 UTC
Labels: fall-cleaning, fixed?, irreproducible
