### ISSUE TITLE
[Table] Column headers scroll off screen

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1021] opened 2016-06-16 22:58 UTC
Column headers for a real-time or historical table are in the scrolling region, meaning that if a user scrolls down to see data, they can no longer tell what the columns are. This can impair usage of tables, particularly when there are many columns: You scroll down, see a row you're interested in, and have to scroll away from it to interpret it fully.

It would be preferable for table headers to stay in place, and for the scrollable area to effect just the rows.

Noted during testathon 2016-06-16

Loosely related to #562

**Comment by goelrohan6** [comment] 2016-09-06 10:44
@VWoeltjen can you tell me in which file the change is to be made, as I do not know the directory structure much.

**Comment by hudsonfoo** [comment] 2016-09-06 11:02
Likely under /platform/features/table

**Comment by hudsonfoo** [comment] 2016-09-06 12:23
@goelrohan6: It looks like you can get at least close to the finish line by updating the `.mct-table` class in /platform/features/table/res/sass/table.scss starting at line 36:

```diff
.mct-table {
    table-layout: fixed;
    thead {
        display: block;
+       position: fixed;
+       background-color: rgba(71,71,71, 1);
+       z-index: 1;
        tr {
            display: block;
            white-space: nowrap;
            th {
                display: inline-block;
                box-sizing: border-box;
            }
        }
    }
```

Which results in: http://quick.as/3ajio6zZ

You'll likely want @charlesh88's input and I have not tested the above in anything other than Chrome desktop. I hope this helps!

**Comment by goelrohan6** [comment] 2016-09-07 06:40
@hudsonfoo @VWoeltjen shall I create a pull request for the issue if anything else is not to be done ?
I guess that a form has to be filled before contributing ..

**Comment by charlesh88** [comment] 2017-09-18 20:14
Closing as dupe of #1481

**Closed by charlesh88** 2017-09-18 20:14 UTC
