### ISSUE TITLE
[Create] Locator sometimes comes up empty

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#491] opened 2016-01-19 19:32 UTC
The locator ("Save In") field in a Create dialog sometimes comes up empty since NEM integration.

**Comment by VWoeltjen** [comment] 2016-01-19 19:33
Believe this has something to do with [root-hiding behavior](https://github.com/nasa/openmctweb/blob/068d4e7d43f56b6e84b4f95e514c8cf8d307147f/platform/commonUI/edit/src/capabilities/EditableContextCapability.js#L66-L73) of wrapped context capability

**Comment by VWoeltjen** [comment] 2016-01-19 19:50
@akhenry / @charlesh88 - If I'm correct about the root cause, the original rationale for this code was to prevent changes "outside" of the object being edited.

The specific case which brought this up was Timeline editing. Desired behavior when clicking the Add button for an Activity or Timeline was that you'd see the "Save In" part of the dialog, but that your save-in options would be restricted to only the timeline and its contents (e.g. not some other place in the folder hierarchy.) It's not clear to me if this is still the desired behavior under NEM.

Still need to verify that this is the root cause of what is happening, and if it is, to understand why it only happens sometimes. Believe there may be a race condition involved (e.g. object is wrapped as editable before dialog is shown, sometimes). Will try to resolve without breaking other functionality.

**Comment by akhenry** [comment] 2016-01-19 20:57
```
The specific case which brought this up was Timeline editing. Desired behavior when clicking the Add button for an Activity or Timeline was that you'd see the "Save In" part of the dialog, but that your save-in options would be restricted to only the timeline and its contents (e.g. not some other place in the folder hierarchy.) It's not clear to me if this is still the desired behavior under NEM.
```

This makes perfect sense to me, and I think should remain the desired behavior in NEM.

A race condition is plausible, as I recall there is a timeout in the LocatorController. My understanding however was that the problem could be reproduced consistently on certain object types? Also, to be clear, this is only occurring in Vista? It has not been observed in Open?

**Comment by VWoeltjen** [comment] 2016-01-19 22:20
Have not observed this in open. That was part of what was driving me toward thinking it was timing-related (since open is typically persisting to Browser Local Storage, giving very different timing characteristics when interactions with persistence are involved.)

Debugging, I no longer believe this to be the root cause. In particular, I'm observing that there [is no `context` capability](https://github.com/nasa/openmctweb/blob/d6fe543c16ba32c637b2106aaf3da07e0e49929b/platform/commonUI/browse/src/creation/LocatorController.js#L43) at all for the object that is being used to initialize the locator.

Notably, the object in this case is missing a `location` property. It can't be assigned a `context` by the [LocatingObjectDecorator](https://github.com/nasa/openmctweb/blob/d6fe543c16ba32c637b2106aaf3da07e0e49929b/platform/entanglement/src/services/LocatingObjectDecorator.js). Which should be fine, because I would expect the [CompositionCapability](https://github.com/nasa/openmctweb/blob/d6fe543c16ba32c637b2106aaf3da07e0e49929b/platform/core/src/capabilities/CompositionCapability.js#L127) to contextualize these before they are presented in the tree. (If that isn't happening, I think we may encounter another class of bugs where context-sensitive actions on links do not behave as expected, e.g. Remove)

**Comment by VWoeltjen** [comment] 2016-01-19 22:23
...and I don't see incorrect behavior when I Remove a Link, so I'm back to being quite uncertain about why this is happening (aside from that a missing `context` is involved.)

**Comment by VWoeltjen** [comment] 2016-01-19 22:24
Also, should add that this no longer appears intermittent - I only see this on specific objects now (specifically, when I Create something while a location-less object is selected.) Some other change has resolved the other cases of this that we were seeing.

**Comment by akhenry** [comment] 2016-01-19 22:28
> Debugging, I no longer believe this to be the root cause. In particular, I'm observing that there is no context capability at all for the object that is being used to initialize the locator.

Oh, yeah, that would make sense. Telemetry points do not have location (at least in Vista, but this may also be the case in WARP) because I believe they're all considered links. It should be possible to reproduce this in open with telemetry points. I'll try it with my MSL/REMS branch.

Andrew

**Comment by VWoeltjen** [comment] 2016-01-19 22:32
> I'll try it with my MSL/REMS branch.

Good thinking. Trying this with `example/taxonomy` (which doesn't include `location` properties) and am unable to reproduce. Think this is about more than just the absence of a `location` property, but not sure what else might be coming into play

**Comment by VWoeltjen** [comment] 2016-01-19 23:10
A little bit bizarre - when I select the same object in the tree and hunt it down on console with `angular.element(document.querySelector('.selected').childNodes[3]).scope().domainObject`, the object _does_ appear to be contextualized. So it appears that whatever goes wrong, goes wrong between the selection in the tree and the instantiation of the Create action(s)

**Comment by VWoeltjen** [comment] 2016-01-19 23:21
Domain object is contextualized at the time of CreateAction#perform, but not at the time of SaveAction#perform

**Comment by akhenry** [comment] 2016-01-19 23:37
Hrm...I don't know if it's relevant, but the parent of the domain object is [fetched manually](https://github.com/nasa/openmctweb/blob/master/platform/commonUI/edit/src/actions/SaveAction.js#L149) in SaveAction because context capability may not be available (in the case of new object). In fact it makes an assumption here about the presence of location, so I'm not sure what the effect of location being missing would be here, but probably not good.

**Comment by VWoeltjen** [comment] 2016-01-19 23:38
Okay, _can_ reproduce in open now. (I just needed to pull :facepalm:)

To reproduce: 

* Run with `example/taxonomy` enabled (need to add this in `main.js`)
* Go to http://localhost:8080/#/browse/exampleTaxonomy/examplePacket2/exampleTelemetry0
* Create > Folder

Observe:

![open491](https://cloud.githubusercontent.com/assets/1685764/12435284/705b2480-bec1-11e5-958c-f972d2b84137.png)

Notes:

* [In CreateAction#perform](https://github.com/nasa/openmctweb/blob/fcc3752ba24e578d8af91f7b40243103e538b5b0/platform/commonUI/browse/src/creation/CreateAction.js#L94), `parentObject` is a contextual domain object.
* [In SaveAction#perform](https://github.com/nasa/openmctweb/blob/fcc3752ba24e578d8af91f7b40243103e538b5b0/platform/commonUI/edit/src/actions/SaveAction.js#L131), `domainObject` is not a contextual domain object.

CreateAction#perform calls SaveAction#perform in this case. More specifically, it instantiates a new domain object, then invokes save on that.

@akhenry, now that this is reproducible in open, mind if I reassign back to you? You'd be more familiar with this area of code

**Comment by akhenry** [comment] 2016-01-19 23:39
@VWoeltjen Yes, please do

**Comment by VWoeltjen** [comment] 2016-01-19 23:47
> Hrm...I don't know if it's relevant, but the parent of the domain object is fetched manually in SaveAction because context capability may not be available (in the case of new object). In fact it makes an assumption here about the presence of location, so I'm not sure what the effect of location being missing would be here, but probably not good.

Ah, that sounds very much like it could result in this. Now that the order of things is changed (dialog gets shown on Save instead of on Create), I think we should consider passing along the object that was selected at the time of Create in a different way. 

Using `domainObject`/`selectedObject` in Save's ActionContext (consistently with drag-and-drop) could be useful here. e.g. in CreateAction, invoke save as:

```
return parentObject.getCapability('action').perform({
    key: 'save',
    selectedObject: editableObject
});
```

...then, Save would have easy access to the initial location. Not sure how that would/should play out in cases where Save is invoked in different cases, however

**Comment by akhenry** [comment] 2016-01-20 18:03
@VWoeltjen Good suggestion, thanks. I've implemented it and it solves some cases. The problem is that the SaveAction is invoked either by CreateAction (for a newly created object that does not go into edit mode), or by pressing the save button from within edit mode. In the latter case, if the object has been newly created it will have no context, and there will be no `selectedObject` provided.

Using the Taxonomy example:
1. I select __exampleTelemetry0__. 
2. I then click __Create__, and select a __Display Layout__. 
3. A new __Display Layout_ object is created, and navigated to. Now nothing is selected in the tree.
4. I click save. The `SaveAction` is invoked, without a `selectedObject` (not because nothing is selected, but because the SaveAction was invoked by a button click). In this case I can't use the getParent approach either because the new DisplayLayout object has no location yet.

For these cases, I wonder if the Locator should default to a root context if no context is available? This is going to happen with new objects.

There is another problem - the case of a newly created timeline. 
1. A new __Timeline__ object is created, and automatically navigated to in edit mode
2. User adds a new __Activity__
3. Neither the Timeline, or Activity have context. `Activity.location` = the new Timeline, however attempts within the Locator to use the `ContextCapability` of the new action will fail because new objects do not have context.

**Comment by larkin** [comment] 2016-01-20 18:06
+1 for locator default root context when context isn't provided.  Reasonable defaults, but can be controlled by whatever is instantiating the locator.

**Comment by akhenry** [comment] 2016-01-20 18:15
My second example is problematic because even defaulting to a root context won't fix it. The user should not be able to select where to place it because it must go under the __Timeline__ object when in edit mode.

Here's a crazy idea - We don't use the locator at all. The location is determined by the object selected at create time, or by the parent (in the case of timelines and other cases where it's possible to create sub-objects from edit mode). It's the same way creating a new file works in finder, you navigate to where you want to create it first.

**Comment by VWoeltjen** [comment] 2016-01-20 18:22
> For these cases, I wonder if the Locator should default to a root context if no context is available? This is going to happen with new objects.

Yes, that's reasonable. I've preferred to avoid that (to minimize the extent that any given unit needs to "know" about the system) but having sensible fallback behavior here would be useful, and this is the simplest way to provide that.

I think that's not a whole solution, however. The "Save In" should really default to the place where you had created the object, whether you did some editing first or not. We have this information at the time editing starts, so we just need to make sure we retain it.

What we don't really have right now is an object that represents "the current editing session." That might be useful here (although I'm not sure how well that would work in cases where we're just editing an existing object, rather than creating it)

> Here's a crazy idea - We don't use the locator at all. The location is determined by the object selected at create time, or by the parent (in the case of timelines and other cases where it's possible to create sub-objects from edit mode). It's the same way creating a new file works in finder, you navigate to where you want to create it first.

I think there are some UX gotchas there (when a user hits "Create" do they mean "Create Here"? Or do they just know what they want to Create, and want to think about where to put it later? I think both happen.) Regardless of that, if we have a reference to the object selected at create time when we complete the save, wouldn't we be able to use that to prepopulate the Locator?

**Comment by larkin** [comment] 2016-01-20 18:30
We're refactoring things-- things will break but we have to keep the end goal in sight.

It's clear to me that our actions are not as flexible or reusable as we would like them to be.  I really think we need to stop complicating them and just have multiple different create actions depending on context and usage.  Otherwise this code is getting harder and harder to maintain due to overloading with concerns.

The general case for creating a new object (especially when not in edit mode) is that it should default to the location selected, unless the object is not a valid container, in which case it should default to root and expect user to choose a location when they save.

IMO, Create activity while editing timeline should not have a locator-- should just force it to be contained in the current timeline.  this is more of an issue with sub object editing, which we can push off.  Short term, it seems a small hack and override of the create action for timelines would resolve this issue.

**Comment by akhenry** [comment] 2016-01-20 18:39
Yeah, I agree. Create and Save need to be prised apart. I reused the save action from create because it was the path of least resistance at the time, but I think it's causing more pain now than it's saving. It means some duplication (both create and save may show wizard), but I think that's ok.

I could also add a new "AddAction" (or CreateSubObjectAction) to create from within a Timeline.

Again, duplication, but the nexus of all of these cases in SaveAction is causing spaghettification of code.

**Comment by akhenry** [comment] 2016-04-04 17:20
I believe that this issue is resolved. Marking as unverified to test in next testathon.

**Comment by VWoeltjen** [comment] 2016-04-18 22:09
Verified in testathon 20160418, can no longer reproduce except in the case of the Add dialog (which is accounted for by #674)

**Comment by charlesh88** [comment] 2016-04-18 22:55
Testathon 041816
Cannot reproduce after trying to create multiple types of objects whilst having selected multiple types of current containers.

**Closed** 2016-04-18 23:50 UTC
