### ISSUE TITLE
Editing Properties then cancelling throws console error

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3264] opened 2020-08-03 22:38 UTC
Right click an object with editable properties in the tree and select "Edit Properties", do or don't make any change to the editable properties and then cancel instead of clicking "ok".

Error thrown in the console: Possibly unhandled rejection: undefined (angular.js)

![Screen Shot 2020-08-03 at 3 33 41 PM](https://user-images.githubusercontent.com/12013460/89233853-5de49800-d59f-11ea-88fa-a5e98b0a5804.png)

![Screen Shot 2020-08-03 at 3 34 02 PM](https://user-images.githubusercontent.com/12013460/89233856-61781f00-d59f-11ea-83cf-3f8653f5f3cc.png)

**Comment by ozyx** [comment] 2022-09-30 22:50
Closing as dupe of #4864

**Closed by ozyx** 2022-09-30 22:50 UTC
