### ISSUE TITLE
[Save] Save As... displayed when editing an existing object.

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1275] opened 2016-10-21 22:06 UTC
Seen during Testathon 2016-10-21, and pretty sure I saw this running master locally as well. 
1. Create any object that allows editing and save it.
2. From browse, click to edit it.
3. Observe: Save As... button is displayed, but should be dropdown Save button.

![screen shot 2016-10-21 at 3 04 21 pm](https://cloud.githubusercontent.com/assets/1056412/19613190/f1fe735e-979f-11e6-9a38-f6dda4f7c32b.png)

This only seems to be occurring with fairly new objects - old objects don't exhibit the problem.

**Comment by akhenry** [comment] 2016-10-21 23:04
Might potentially also be a model sync issue. Seems to only affect new objects. Save/Save as logic is based on `persisted` attribute of model, so if a component has a pre-persistence version of the model the `persisted` won't be set. If that's the case though, it's a little strange that other model attributes like composition etc appear to be correct...

**Comment by akhenry** [comment] 2016-10-21 23:07
May also be related to the fix for #1080

**Comment by larkin** [comment] 2016-10-21 23:26
Browser refreshes are not resolving the issue, so perhaps not setting the persisted attribute for new objects, unsure.

**Comment by larkin** [comment] 2016-10-21 23:28
Scheduling for Robinson.

**Comment by larkin** [comment] 2016-10-21 23:41
Refreshing does fix.

**Comment by larkin** [comment] 2016-10-25 18:13
Assigning to @akhenry for investigation, expect may be related to #1282.

**Comment by larkin** [comment] 2016-10-27 21:27
I don't believe this is related to #1282; in testing the issue is not that changes fail to be detected; the issue is that the persisted attribute is not getting updated in memory, but the changes are being written to the server.  I expect this is a result of #825, though further research is necessary.

**Comment by larkin** [comment] 2016-11-09 00:27
Should be closed with #1316, closing to verify.

**Closed** 2016-11-09 00:28 UTC
Labels: bug, critical, unverified

**Comment by charlesh88** [comment] 2016-11-10 00:32
Testathon 11-09-2016: verified fixed.
