### ISSUE TITLE
Rollup TSC. ES6 ./src update

### ISSUE THREAD

**Issue by shaynababe** [nasa/openmct#6582] opened 2023-04-11 23:37 UTC
testing update code

Im not sure this is helpful for NASA i hope it is

the code based does have some errors based on the github code maybe it is not used in the production bld , not all of it
[rollup.config.js.txt](https://github.com/nasa/openmct/files/11205565/rollup.config.js.txt)

I now have babel 8 working and eslint up and running the TSC code has far less errors and much smaller
I have to bundle the code in segments my computer has memory node fails , this is still in work, Commonjs has commonjs[{strictRequires:'false'},{transformMixedEsModules:'true'}],
to assist rollup has changes to the code also how it does bundles and what plugin you have , Bable and eslint will be very helpful in getting error corrected before bundled
[tserr.txt](https://github.com/nasa/openmct/files/11205574/tserr.txt)
the Plugin got done still have to review, it does not appear to be like api

**Comment by unlikelyzero** [comment] 2023-04-13 17:45
Thank you for finding and filing this issue!

The Open MCT team has identified this issue as a duplicate of an existing issue. To follow along with that development (or contribute!), please subscribe to the following: https://github.com/nasa/openmct/issues/6591

**Closed by unlikelyzero** 2023-04-13 17:45 UTC
Labels: type:maintenance
