### ISSUE TITLE
Tree not updating to reflect composition changes

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3421] opened 2020-10-05 21:41 UTC
An object's composition displayed in the tree should be updated after editing is completed, but it _sporadically_ doesn't.

### Steps to reproduce
1. Create a new Overlay plot.
1. Add two telemetry points to it. Save and Finish editing.
1. Go back into the plot and remove one of the telemetry points. Note that the tree isn't updated - that's Ok, we haven't saved yet.
1. Save and Finish editing. Observe in the tree that the removed telemetry point _may_ remain visible in the tree (red arrow in attached screenshot below):
<img width="691" alt="Screen Shot 2020-10-05 at 2 27 31 PM" src="https://user-images.githubusercontent.com/1056412/95135006-a8f26700-0718-11eb-8c36-25c94b7e624c.png">

**Comment by jvigliotta** [comment] 2020-10-07 17:47
Couple things I'm noticing while digging into this:

- when deleting from the inspector (right click -> remove) the item stays in the inspector (as well as the tree, which is expected since no save yet)
- upon save, the item is not removed from the tree because the composition 'remove' event is not triggered
  - while observing the object, you can see the item was removed from the composition (even when it has not been saved yet)
- if you remove the item using the inspector (like above), then cancel out your changes, it seems the items composition 'add' event is triggered and you get a duplicate of the item in the tree
- all of those issues are resolved if you navigate away from the current plot and back into it, it's composition is loaded correctly

Seems there's some issues with composition add/remove events when removing items using the inspector?

**Comment by akhenry** [comment] 2020-10-08 17:12
Potentially fixed by https://github.com/nasa/openmct/pull/3431

**Closed** 2020-10-08 17:12 UTC
Labels: Target: 1.3.2, blocker, bug, unverified

**Comment by nikhilmandlik** [comment] 2020-10-09 17:22
Verified Fixed. Testathon 10/09/2020

**Comment by davetsay** [comment] 2020-10-09 17:39
Verified
