### ISSUE TITLE
[Edit Mode] Navigation confirmation not working as expected with new objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1278] opened 2016-10-21 22:24 UTC
1. Create a new layout, fix position display, or panel.
2. Drag some objects into it
3. Click on another object to navigate to it.

No confirmation dialog is shown.

**Comment by larkin** [comment] 2016-10-21 22:36
Imagine this is related to #1277, though in #1277 I was seeing the confirmation message when navigating.

**Comment by larkin** [comment] 2016-10-24 19:54
@akhenry to investigate.

**Comment by larkin** [comment] 2016-10-27 20:54
On review, I think this is not related to #1277.  I cannot reproduce #1277 after merging #1301, but I can still reproduce this bug.  I'm guessing it is either related to change detection or the removal of persistence calls, but YMMV.

**Comment by larkin** [comment] 2016-11-09 00:27
Should be closed with either #1301 or #1316, closing to verify.

**Comment by charlesh88** [comment] 2016-11-10 00:27
Testathon 11-09-2016: verified NOT fixed. 
- Created new FP object, dragged existing telem points into canvas area. Clicked another object in tree and search results; navigated to object without confirmation dialog.
- Same for new Layout after dragging in another existing Layout.

**Comment by larkin** [comment] 2016-11-10 18:07
Re-opening as not-fixed.

**Comment by akhenry** [comment] 2016-12-05 22:50
Appears to be due to [this line](https://github.com/nasa/openmct/blob/68d6920d3808bebf9b0acb61c865e3318835a1ba/platform/core/src/runs/TransactingMutationListener.js#L43) The TransactingMutationListener only adds a persist call to the current transaction if the object has previously been persisted. Thus when a dirty check happens on navigation, the persist queue is empty.

**Comment by akhenry** [comment] 2016-12-05 22:56
@VWoeltjen Do you recall what the original reason was for this logic?

**Comment by VWoeltjen** [comment] 2016-12-05 23:14
Not specifically (I wrote a rather unhelpful commit message there.) I believe I was seeing some undesired behavior on Create of certain objects, but don't recall the specifics. Creating a Timeline and adding a few Activities before saving it would be a good way to exercise this (in addition to the simpler Create Folder and Create Display Layout cases.)

There are some persistence/caching-related behaviors that have been corrected since then (e.g. #1316) so it's very plausible that this logic is no longer necessary. Think it would be very reasonable to remove that check and test around for any misbehavior associated with it.

**Comment by akhenry** [comment] 2016-12-05 23:19
@VWoeltjen ok great, thanks for the info. I did try the cases you mention, including deeply nested activities and found no strangeness, but I thought it best to check with you before I remove it.

I agree, whatever it was may have been rectified by other means since this was implemented.

**Comment by akhenry** [comment] 2016-12-05 23:58
Closed via accidental commit directly to master. Reopening for review in #1347

**Closed** 2016-12-06 21:50 UTC
Labels: bug, critical, unverified

**Comment by charlesh88** [comment] 2017-02-07 19:07
Testing notes for Testathon 02-07-2017:

1. Create a new Display Layout.
1. Drag in a telemetry point, other objects.
1. Click on another object in the tree to navigate away.
4. Observe: the application should display the unsaved changes warning dialog, and should NOT merrily navigate away.

**Comment by charlesh88** [comment] 2017-04-20 23:04
Testathon 2017/04/20 Verified fixed.
