### ISSUE TITLE
[Inspector] Elements slow to update after drag-and-drop

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1881] opened 2018-01-16 22:21 UTC
Observed during VISTA R3.4 RC1 testing.

Create > Telemetry Table. Drag and drop one or more channels into the empty table. Observe that nothing appears in the table, and the following error appears on console:

```
:8443/mcws/clients/vista-r34-test/openmct/openmct.js:57 TypeError: Cannot read property 'forEach' of undefined
    at t (:8443/mcws/clients/vista-r34-test/openmct/openmct.js:37)
    at new i (:8443/mcws/clients/vista-r34-test/openmct/openmct.js:37)
    at o.getMetadata (:8443/mcws/clients/vista-r34-test/openmct/openmct.js:37)
    at Array.map (<anonymous>)
    at o.loadColumns (:8443/mcws/clients/vista-r34-test/openmct/openmct.js:57)
    at n (:8443/mcws/clients/vista-r34-test/openmct/openmct.js:36)
    at <anonymous>
```

**Comment by VWoeltjen** [comment] 2018-01-16 22:24
After filing the issue, the elements I'd drag-dropped appeared in the Elements pool and I was able to save the Table. Subsequently it behaved as expected, although the above error does show up on console again

**Comment by VWoeltjen** [comment] 2018-01-18 21:23
From the stack trace, it looks like same exception that #1779 was intended to address. That was closed unmerged with the comment:

> Since we haven't seen this issue in production, I'm going to assume it only effects malformed legacy objects and I will close this PR

Silly me. In any case, this makes the behavior more confusing. I'll try to reproduce.

**Comment by VWoeltjen** [comment] 2018-01-18 21:27
The console error appears to have been unrelated. What I see is that table column headers populate, no data shows in the table (which is correct for time conductor config), and the Elements pool takes an awfully long time to update to show the dropped object.

I see this behavior with the Elements pool elsewhere, so I think this is unrelated to tables. Will retitle.

**Comment by akhenry** [comment] 2018-01-18 21:34
@VWoeltjen Ahhhh, yep, I was beginning to wonder the same thing. In my attempts to reproduce this I have seen a number of error messages in tables, so I will create some issues for them.

**Comment by psarram** [comment] 2018-01-19 19:49
@VWoeltjen @akhenry I cannot reproduce the issue when dropping a sine wave generator to an empty table. The Elements pool updates immediately. Where else have you seen the behavior where Elements is slow to update?

**Comment by akhenry** [comment] 2018-01-19 20:01
@psarram Ah, it looks like the issue happens if you're already in edit mode. If you're in browse mode and you drop a new element in then the transition from browse to edit mode seems to refresh the inspector (it triggers a digest maybe?).

So, try editing a table first (or creating a brand new table) and then dropping the SWG in.

**Comment by larkin** [comment] 2018-03-02 23:19
Closing: This is a dupe of #1869, which has been closed.

**Closed by larkin** 2018-03-02 23:19 UTC
