### ISSUE TITLE
Allow creation from object context menu

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#531] opened 2016-01-21 21:44 UTC
<p>Allow the user to create a new item within an existing item, while in Browse mode, via a contextual menu for that item. The menu must be appropriate to the containing item; in other words, it must display the same options that the Create button menu displays for a given selected object.</p> <p>This should be added to the UI design doc as a feature.</p> <p>Testathon 1/29/15</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-775
Originally created: Thu, 29 Jan 2015 15:22:56 -0800
Updated: Thu, 7 Jan 2016 13:16:47 -0800

**Comment by larkin** [comment] 2016-06-16 22:13
I just watched @akhenry right click on a folder and attempt to make something.

Five minutes later, I right clicked on a folder and attempted to create an object.

We should add this.

testathon 2016-06-16

**Comment by akhenry** [comment] 2016-06-16 22:15
Would like to discuss in next sprint planning, so setting milestone to Le Guin for now. Can remove if necessary after planning.

**Comment by charlesh88** [comment] 2016-06-17 00:14
Agree if this doesn't take a lot of time away from more important issues. I'd rank #977 above this for example.

**Comment by BogdanAlexandru** [comment] 2017-02-25 17:14
For anyone interested in the issue: 

Relevant files to open up when starting on this are:
/platform/commonUI/general/res/templates/menu/context-menu.html
/platform/commonUI/general/src/controllers/ContextMenuController.js
/platform/commonUI/edit/res/templates/create/create-menu.html
/platform/commonUI/edit/src/creation/CreateMenuController.js

To see how context menus get built, and how creation actions are introduced in the create menu. By the looks of it this issue will also include a rework of context menus; right now they're linear lists of actions, and I believe for this we need a nested structure.

```
Create   -->  New Folder
Option 1      Display Layout
Option 2      Fixed Layout
...           Some other thing
              Yet another thing
              ...

```

Figuring out how to bring the create actions into the context menu is the second part.

**Comment by charlesh88** [comment] 2017-03-20 18:51
@BogdanAlexandru You are right on target with the multiple context menus. For example, here's an older design that shows the main context menu for an object:

![screen shot 2017-03-20 at 11 47 08 am](https://cloud.githubusercontent.com/assets/1056412/24116162/11543e94-0d63-11e7-84e4-efc66c645246.png)

If the user moused over the "Create and Add >" menu item, they should see an additional flyout menu that displays a filtered list of objects that can be contained by the object that spawned the main context menu. This sub-menu should look like a normal context menu, vs. trying to recapitulate the Create menu. Note as well that menu position in relation to the browser window edge must be taken into account: the sub-menu must handle circumstances where the main context menu is rendered close to the bottom or right of the browser viewport.

**Comment by charlesh88** [comment] 2017-09-18 17:57
This covers #280.

**Comment by larkin** [comment] 2017-09-18 19:37
Consider this a duplicate of https://github.com/nasa/openmct/issues/354.  Merging.

**Closed by larkin** 2017-09-18 19:37 UTC
Labels: help wanted
