### ISSUE TITLE
[Indicators] Minimized status bar messages remain in the DOM

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#443] opened 2015-12-17 22:37 UTC
When a status bar message is minimized, it uses CSS to animate it to the bottom left and fade it out. It still remains in the DOM, however, and grabs cursor events when the user mouses around other indicator icons in the status bar. Clicking the minimized message displays the message's overlay, when the user thought they were clicking an indicator icon. 
The minimized message should be destroyed and removed from the DOM after it has transitioned.

**Comment by charlesh88** [comment] 2015-12-17 22:37
Put this in Baxter just to get it on the radar.

**Comment by akhenry** [comment] 2016-08-06 00:17
Unable to reproduce the observed behavior on my machine, or the linux machines in the lab. Closing and marking unverified to see if it can be reproduced in the testathon.

**Closed by akhenry** 2016-08-06 00:17 UTC
Labels: bug

**Comment by charlesh88** [comment] 2016-08-08 22:10
Testathon 08-08-2016: can't reproduce; call it fixed.

**Comment by VWoeltjen** [comment] 2016-08-08 22:28
Verified testathon 20160808

**Comment by Costigan** [comment] 2016-08-08 23:30
Can't reproduce.
