### ISSUE TITLE
minmax strategy should not be sent on plots not using a line style

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2381] opened 2019-04-13 03:43 UTC
current plot behavior is to send the minmax strategy on all overlay plots, even those not choosing to use linear interpolation or step after. 

Minmax is only a valid strategy on plots with linear interpolation or step after as the plot option. 

Correct behavior should be to send undefined as the strategy type for this kind of plot. 

This is starting to affect plots where I have to use a minmax strategy (most missions I'm not sending minmaxed data)

**Comment by deeptailor** [comment] 2019-09-05 20:03
closing as dupe of #2469

**Comment by akhenry** [comment] 2019-09-10 21:35
Not a dupe, this is the issue that prompted the PR.

**Comment by akhenry** [comment] 2019-09-10 21:36
@mudinthewater We have a candidate fix for this. It needs to be reviewed and merged, but it should be in topic-core-refactor very soon.

**Comment by akhenry** [comment] 2019-09-10 21:38
Moving detail from https://github.com/nasa/openmct/issues/2468 and closing that as dupe.

By default, Plots will always issue a "min-max" type request for historical data in order to limit the amount of data that needs to be retrieved from the server. This works well for linear plots which will interpolate between the given points.

Users can switch this off by creating an Overlay plot, dragging in some telemetry, and selecting a line style of "None". If they switch "Markers" on, then the plot will only show markers for the telemetry values, and will not draw lines in between them. In this mode, the plot is essentially a scatter plot. Users have reported confusion when seeing min-max values in this case, and are expecting to see points for all available telemetry values.

To address this we should:

Make a change to Plots so that when a request for historical telemetry is issued, the request strategy should not be set to min-max.
Add a listener that reacts to changes in plot configuration and checks whether the 'line style' configuration has changed (Plots do something similar for filter changes). If it has, then a new request for telemetry data should be issued with the request strategy being set appropriately (ie. min-max in all cases except when the line style is none). Ideally only the plot series that has been modified should be re-requested, but if this is too complex, then it is acceptable for all plot series to be discarded and re-requested.

**Comment by mudinthewater** [comment] 2019-09-10 21:38
@akhenry Thanks!

**Comment by deeptailor** [comment] 2020-04-14 17:29
closing as fixed

**Closed by deeptailor** 2020-04-14 17:29 UTC
Labels: Target:VISTA-R4.3
