### ISSUE TITLE
Table rendering while in progress looks broken

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#972] opened 2016-05-26 20:05 UTC
In latest master branch, while loading a Historical table view (populated by an SWG) or looking at the tabular view of an SWG, the table itself looks bad until it gets populated with data. Additionally, no wait spinner appears, but should. This can be seen with [sample data in the live demo](https://openmct-demo.herokuapp.com/#/browse/demo:realtime/be3d5df3-cc6e-4b8b-9865-fcd844e55b94/195ca42c-285c-4e3b-afd3-d530ad959bb0/2910cf8f-c1d9-4153-b3ab-0d18108f6cc4?view=table), but it happens much faster, probably due to less data.

Examples:

#### If an object with that view is the selection when reloading the app. 
Note that the tabular view overruns the tree to the left, and the columns have not been sized yet.

<img width="1794" alt="screen shot 2016-05-26 at 12 47 04 pm" src="https://cloud.githubusercontent.com/assets/1056412/15587953/7ee24112-2340-11e6-973e-1c9a64813b6f.png">

#### Clicking on the tree to load the table:
<img width="1794" alt="934 table not sized" src="https://cloud.githubusercontent.com/assets/1056412/15588002/b644f3f2-2340-11e6-95af-e90aa64d8964.png">

What is expected:
* Don't show the table (headers included) until it has had it columns sized and is properly positioned.
* Display a wait spinner while the table is resizing and being populated with data.

Recommend we add .loading to the container (mct-rep?) above the table, then I'll add a CSS rule that sets the opacity of the table to 0 while it's loading. Note that we probably don't want to use display: none here as that wouldn't allow the sizing table to function properly.

**Comment by akhenry** [comment] 2016-05-26 21:20
Not sure why the table is positioned so strangely, but looks like there is a blocking process that is preventing the app from initializing completely, or blocking a transition or something. If this is the case, then I expect we would see the wait spinner strangely positioned as well. It would also block the animation thread, so the spinner wouldn't spin. It might be caused by processing a large number of historical records. I'll play around a bit and try and see if I can figure out what's going on.

@larkin Is the wait spinner typically applied on a per-view basis, and is this the case with VISTA?

**Comment by akhenry** [comment] 2016-05-26 22:25
Did some testing, it looks like it is client side processing of large historical data records blocking the UI thread to block. There are two approaches

1. Look at optimizing the processing code for historical tables to see if there are any obvious bottlenecks. 
Or
2. I've done some testing with a yielding loop function that periodically calls a timeout to yield to the UI thread before resuming processing. Doesn't seem to increase processing time too much, and results in an animated wait spinner and correctly rendered UI.
Or
Both.

**Comment by VWoeltjen** [comment] 2016-05-26 22:58
I'd vote for Option 2 in this case - getting back UI responsiveness is higher priority.

Partly that's motivated by some quick profiling; there's a big cost to addHistorical but it's split up among a few different steps (as opposed to one bad loop-within-a-loop or something).

**Comment by akhenry** [comment] 2016-05-26 23:01
@VWoeltjen already on it.

**Comment by charlesh88** [comment] 2016-05-26 23:02
Seconded, thanks.

Sent from my iPhone

On May 26, 2016, at 3:58 PM, Victor Woeltjen <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd vote for Option 2 in this case - getting back UI responsiveness is higher priority.

Partly that's motivated by some quick profiling; there's a big cost to addHistorical but it's split up among a few different steps (as opposed to one bad loop-within-a-loop or something).

**Comment by larkin** [comment] 2016-05-26 23:58
Loading is typically handled by the component that is doing the async work. In this case the controller knows when the request has completed and all the data has been added and is in the best place to toggle loading on/off. 

are we triggering a digest per row of data? If there are large numbers of inserts, we should debounce the digest-- that might be what causes such significant latency. 86400 inserts shouldn't be such a large performance hit.

**Comment by akhenry** [comment] 2016-05-27 00:06
@larkin not knowingly, but it's possible that there are some $ functions hidden away in there. I'll take a look.

**Comment by akhenry** [comment] 2016-05-27 00:32
@larkin I don't believe it's triggering digests, see attached

![screen shot 2016-05-26 at 17 30 06](https://cloud.githubusercontent.com/assets/4215777/15594140/b9dca6c8-2367-11e6-8402-edafcbf6f833.png)

**Comment by akhenry** [comment] 2016-05-27 00:33
It's just spending too much time processing each row, but it's all within one long digest. The smaller function calls you can't see in this picture are doing formatting etc. there are no digests within the larger one.

**Comment by larkin** [comment] 2016-05-27 00:41
Ah, I looked at this when I was prototyping new telemetry API. Turns out moment format is pretty slow, other format calls should be faster. There's room for optimization. Is that what you see?

If so... Short story... "Yield" loop is a great temporary workaround. I think moment formatting needs a closer look for performance concerns, but we can delay that months at minimum :)

**Comment by akhenry** [comment] 2016-05-27 22:01
@larkin yes, Moment format may be the culprit, it looks like it's responsible for about 2/3rds of the per row processing time.

So the solution for this has been a little delayed. Took two rewrites to produce something I was happy with. It's done, but I need to write some unit tests, there are a few edge cases I want to make sure are covered. Will try to get a PR today, but don't think it will be merged before code-freeze.

**Comment by larkin** [comment] 2016-06-14 18:38
Note that this change is also fixing the loading indicator-- there is a related issue in VISTA (https://github.jpl.nasa.gov/MissionControl/vista/issues/344) that will need to be closed as a result.

**Closed** 2016-06-16 18:10 UTC
Labels: bug, critical

**Comment by akhenry** [comment] 2016-06-16 21:54
Note to testers: I don't believe that there is a way of verifying this in WARP because we don't have historical data. Should be verified in VISTA build.

**Comment by VWoeltjen** [comment] 2016-06-16 21:57
Verified in testathon 6/16/2016 (including loading indicator)
