### ISSUE TITLE
Timeline scroll interval glitch

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#981] opened 2016-05-31 21:07 UTC
In testing zooms on timelines, I created a timeline about 11 hours long (Whatever Timeline in RECtestathon Apr21 folder).  As I was in edit mode, I tried zooming out to a level showing about half of the timeline, and then scrolling a bit to the right.  The interaction felt to me like the scroll bar had notches, and each tick it was moving about 2 days.  Would like a smoother scroll, and more properly scaled scroll intervals. I observe similar behavior with the RP15 Timeline Rev A

**Comment by VWoeltjen** [comment] 2016-05-31 21:11
@RCarvalhoNASA - How would you characterize the severity here? Would this impede building timelines at the current scales you're working at?

**Comment by RCarvalhoNASA** [comment] 2016-05-31 21:23
Unfortunately, yes.

**Comment by VWoeltjen** [comment] 2016-05-31 21:28
Believe #978 may be in related code, should consider addressing that in the context of this issue

**Comment by VWoeltjen** [comment] 2016-05-31 23:36
Underlying cause is that the scrollable area for the timeline is greatly in excess of what the actual timeline displays; particularly at higher zoom levels, a small movement in the scroll bar corresponds to a large change in time.

#982 fixes this in normal cases by choosing a scrollable area based on the right edge of the timeline. 25% margin is included to give room for editing.

Even with changes from #982, this is still reproducible in extreme cases (at my monitor size, scrolling becomes impractical for a 50-day timeline when zoomed in to 1-hour labelled tick increments.) Workaround for this case is to click the scroll bar, then use left and right arrow keys to make finer adjustments than the mouse would allow; or, alternately, zoom out to a comfortable zoom level, center on the area of interest, and zoom back in.

**Comment by akhenry** [comment] 2016-06-02 15:53
Maybe we need to do away with browser scroll and introduce our own scrolling widgets for the timeline that can adjust their sensitivity as needed. Or at least add left and right arrows to allow scrolling in increments appropriate to the current zoom level.

**Comment by RCarvalhoNASA** [comment] 2016-06-02 22:39
20160602 Testathon, this seems to be fixed, but it has rebroken https://github.com/nasa/openmct/issues/936

**Comment by charlesh88** [comment] 2016-06-02 22:40
Testathon 2016-06-02
This problem appears to be fixed, but looks like we regressed on #936: Timeline is not zooming on center as expected.

**Comment by VWoeltjen** [comment] 2016-06-02 22:41
Noticed this as well, reopened #817. Have a fix in the pipeline and will restart testathon instance with this in place shortly

**Comment by VWoeltjen** [comment] 2016-06-02 22:46
New testathon instance is available now, with a fix for regression on #817/#936; closing this issue again, will need to reverify

**Closed by VWoeltjen** 2016-06-02 22:46 UTC
Labels: blocker, unverified

**Comment by charlesh88** [comment] 2016-06-16 21:05
Testathon 2016-06-16
Verified fixed.

**Comment by VWoeltjen** [comment] 2016-06-16 22:46
Verified in testathon 2016-06-16
