### ISSUE TITLE
Improve vertical layout of activities in the plan view

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6378] opened 2023-02-28 19:09 UTC
Plan views are difficult to navigate and take up too much vertical space resulting in scrolling.
We need to improve the layout to reduce this.

See: #6113

To achieve this, we can, move activity name display so that it always only renders inside the activity 'rectangles'.
Things to consider are: 
2. How to display an activity name that cannot fit at all when the activity duration is too short.
3. How to display an activity name that fits partially? We could clip the name.

While we're working on this issue, we should also ensure that we are showing the activity name in the inspector properties when an activity is selected. We might want to look at how to address the case where multiple activities are selected as well (talk to UX).

**Comment by charlesh88** [comment] 2023-03-01 19:51
Dupe of #6113

**Closed by charlesh88** 2023-03-01 19:51 UTC
Labels: type:enhancement
