### ISSUE TITLE
Tree does not update when search results are displayed

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#795] opened 2016-03-25 16:44 UTC
1. Select a folder in your tree, expand it.
2. Create a new layout but don't save it yet.
3. enter search terms that cause the folder not to be visible in search results
4. save the layout into the folder.
5. clear search results.  folder you created the object in will not show the new object.

**Comment by VWoeltjen** [comment] 2016-04-05 19:40
Can't reproduce with latest on `master`, believe this was resolved by #756.

**Closed by VWoeltjen** 2016-04-05 19:40 UTC
Labels: bug, unverified

**Comment by larkin** [comment] 2016-04-18 22:16
Can't reproduce in testathon 2016-04-18.

**Comment by charlesh88** [comment] 2016-04-18 22:16
Testathon 041816
Could not reproduce following original Pete recipe, would say this is verified fixed.
