### ISSUE TITLE
[Plots] Plots become unreadable when vertical space is constrained

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1022] opened 2016-06-16 23:03 UTC
Plots can become unreadable when available vertical space is constrained below a useful minimum. Seen during Testathon 2016-06-16, it's particularly apparent with VISTA stacked plots. That said, this is not a new problem...

![screen shot 2016-06-16 at 3 41 10 pm](https://cloud.githubusercontent.com/assets/1056412/16135947/9ed0dc12-33db-11e6-96ae-671b166e01bc.png)
![screen shot 2016-06-16 at 3 59 09 pm](https://cloud.githubusercontent.com/assets/1056412/16135948/a13151f8-33db-11e6-9032-da046c3ed269.png)

Asked @larkin how we determine the number of ticks in a VISTA plot's Y axis:

> enumerated plots: show all values.  other types: it's roughly 5 but will show more or less depending on what sort of value generated nice route numbers.

Solution here is two-fold (like the Spanish Inquisition):
1. Define a min-height CSS property for the plot area. Given the current usual 5 ticks, 120px is looking to be a decent value. Apply this to `mct-plot .gl-plot`.
2. Vary the number of ticks based on the available vertical size of the plot area when we can. This should be dynamic, so as the user scales the window or frame size in a layout, we should add or remove ticks as needed, down to a minimum TBD, which I propose is 2: the upper and lower bounds.
3. For enumerated plots, we should scale the plot area as well. So, if we have 10 enums that must be plotted, and each tick takes 25 vertical px each, that plot's area would need a minimum of 250px in height.

We should implement 1 ASAP, and include 2 and 3 in our strategy as we move forward on #977.

**Comment by VWoeltjen** [comment] 2016-06-16 23:07
Possible dupe of #1020, although this is a more complete solution. Also, #977 covers Part 2 of the solution above.

I like Part 3 of the solution; good case to consider and the approach makes sense. Maybe once those other two issues are addressed, we can retitle this issue to focus on that particular point?

**Comment by larkin** [comment] 2016-06-16 23:08
I think min-height is a great first step; we can improve from there.  other fixes are more detailed and worth revisiting.

I have closed #1020 as dupe.

**Comment by VWoeltjen** [comment] 2016-06-20 22:12
Verified in testathon 6/20/2016 - when I try to make a plot too small to read (e.g. in a Layout), it refuses to become too small and scroll bars appear

**Comment by charlesh88** [comment] 2016-06-20 22:26
Testathon 2016-06-20: verified fixed.

**Comment by RCarvalhoNASA** [comment] 2016-06-20 22:27
Note that the reproduction steps for this were not clear.  I found I could still make a plot too small to show data in a layout, but that's apparently not what this one was about.

**Comment by shobart** [comment] 2016-06-20 22:39
I also tried to replicate it yet another way, and I could make a plot too small to show data by sizing the browser way down.   I don't consider that a bug, though, because I could easily resize the browser back.  The browser did what I considered to be reasonable behavior.

**Comment by charlesh88** [comment] 2016-06-22 18:32
Given that we're changing the minimum height back to a value that allows tick labels to overlap per #1048 and #1049, I'm re-opening this issue.

Per my comment above:
> Vary the number of ticks based on the available vertical size of the plot area when we can. This should be dynamic, so as the user scales the window or frame size in a layout, we should add or remove ticks as needed, down to a minimum TBD, which I propose is 2: the upper and lower bounds.

There is also a use case where we go down to no vertical ticks visible at all.

**Comment by charlesh88** [comment] 2017-04-28 16:12
Will be fixed by #620

**Comment by larkin** [comment] 2018-03-02 23:54
Closed with #1557.

**Closed by larkin** 2018-03-02 23:54 UTC
Labels: bug, plotting
