### ISSUE TITLE
Unable to scroll telemetry tables in Display Layout

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3268] opened 2020-08-03 23:34 UTC
Create a display layout
Drag in a telemetry table that shows data in real time
Save the display layout
Edit the display layout and try to scroll the telemetry table
Expected: The table data scrolls
Observed: The table data does not scroll

**Comment by charlesh88** [comment] 2020-08-03 23:36
Introduced with #3176. 

`.is-editing .c-telemetry-table__body-w`

Two things should be fixed:
- Disable pointer events on tr elements (or whichever element is the actual click handler) in order to allow scrolling.
- Only apply to tables/objects within a Layout.

**Comment by charlesh88** [comment] 2020-08-04 00:21
### Testing Notes
1. Create or edit an existing Telemetry Table; add a data source if one isn't already present.
1. Verify that while in Editing mode rows can be selected and the table can be scrolled.
1. Exit editing mode. 
1. Create or edit an existing Display Layout.
1. Add the table from step 1 to the layout.
1. Verify that clicking in the middle of the table selects that element, but doesn't select any rows.
1. Verify that the table can be scrolled.
1. Verify that columns can be reorganized and that column widths can be modified.

**Comment by akhenry** [comment] 2020-10-05 21:36
Verified fixed 10/05/2020

**Comment by deeptailor** [comment] 2020-10-05 21:46
Verified fixed 10/05/2020

**Comment by davetsay** [comment] 2020-10-05 21:55
Verified

**Comment by jvigliotta** [comment] 2020-10-05 22:04
Verified Fixed - 10/05/2020

Found another issue, on step 8 of testing, I'm getting errors in the console (attached).
![Screen Shot 2020-10-05 at 3 02 11 PM](https://user-images.githubusercontent.com/12013460/95136988-01773380-071c-11eb-9d4c-b62982aa1771.png)

**Comment by shefalijoshi** [comment] 2020-10-05 22:11
Verified on 10/05/2020
While scrolling works, when you reach the bottom of the table the scrollbar gets bumped back to the top.

**Comment by charlesh88** [comment] 2020-10-05 22:26
Verified NOT fixed 10-05-20: rows cannot be selected and table can't be scrolled while editing, but should.

**Comment by charlesh88** [comment] 2020-10-05 23:02
Cannot reproduce the latest problem in local build in both Chrome and Firefox. Inspecting SCSS shows that the CSS causing the problem isn't in latest code. Andrew, Jamie and Dave all didn't see the problem. Now think this is cache-related, and closing as a non-issue.

**Closed by charlesh88** 2020-10-05 23:02 UTC
Labels: Target: 1.3.2, bug, unverified

**Comment by akhenry** [comment] 2020-10-09 17:13
Verified fixed 10/09/2020
