### ISSUE TITLE
Icons not showing correctly

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1973] opened 2018-04-03 16:40 UTC
In the attached screenshot, the SMiller item should be a folder, as should the Older Stuff (and several other items).  Instead, they're getting odd icons here.  This occurred after moving several items from My Items into Older Stuff (by right-click and select Move).

**Comment by RCarvalhoNASA** [comment] 2018-04-03 16:40
![image](https://user-images.githubusercontent.com/5769437/38262740-057d5a52-3723-11e8-85d4-44b7ab23f453.png)

**Comment by akhenry** [comment] 2018-04-03 17:43
Suspect this is the same issue as #1911. They should be investigated at the same time.

**Comment by dtailor90** [comment] 2018-04-03 17:51
@RCarvalhoNASA  - Investigating this, was unable to reproduce using the steps you took. Does it go back to normal after refresh?

**Comment by RCarvalhoNASA** [comment] 2018-04-03 17:58
It did go back to normal after refresh, and did not recur when I moved additional items into the folder.

**Comment by dtailor90** [comment] 2018-04-03 18:00
@RCarvalhoNASA - I will keep an eye on this.

**Comment by RCarvalhoNASA** [comment] 2018-04-17 20:58
This just happened again on banner (latest).  It appeared that the icons were basically getting moved down the list as things got removed from the list (by moving them into the Components subfolder).  Does this mean this is something that happens only with new folders?

**Comment by dtailor90** [comment] 2018-04-17 21:00
@RCarvalhoNASA - This seems to be an issue with all icons, I will have a fix for it soon.

**Comment by dtailor90** [comment] 2018-04-17 21:52
@RCarvalhoNASA - I just pushed a fix for this issue. Sorry for the delay

**Comment by larkin** [comment] 2018-04-20 16:47
Closed in https://github.com/nasa/openmct/pull/1992

**Closed by larkin** 2018-04-20 16:47 UTC

**Comment by larkin** [comment] 2018-05-01 21:38
Testathon 2018-05-01: Verified.

**Comment by charlesh88** [comment] 2018-05-01 21:52
Testathon 2018-05-01 - verified fixed.

**Comment by akhenry** [comment] 2018-05-01 22:00
Testathon 2018-05-01: Verified.
