### ISSUE TITLE
[Timer] Issue creating timer

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#6844] opened 2023-07-26 17:59 UTC
#### Summary
When trying to create a timer in testathon, I'm getting the following error:
```
CreateAction.js:90 DOMException: Failed to execute 'structuredClone' on 'Window': #<Object> could not be cloned.
    at DefaultCompositionProvider.add (webpack-internal:///80249:445:27)
    at CompositionCollection.add (webpack-internal:///80249:711:22)
    at CreateAction._onSave (webpack-internal:///2419:91:29)
```
The timer isn't created and doesn't show up in the tree, even after a page refresh.

**Comment by ozyx** [comment] 2023-07-26 19:41
Closing -- cannot reproduce. THink this was due to cache issue

**Closed by ozyx** 2023-07-26 19:41 UTC
Labels: type:bug, severity:critical
