### ISSUE TITLE
Getting "Missing: mine" rather "My Items" after installing from `master` branch

### ISSUE THREAD

**Issue by klyn** [nasa/openmct#1284] opened 2016-10-23 13:38 UTC
I'm not sure if this is expected or not, but after installing from `master`, instead of "My Items" I see "Missing: mine" in the left sidebar.

All tests are passing and there aren't any errors in the browser console neither. Is that a case of master branch being unstable or it's an expected behaviour after a fresh installation?

`npm install` also was all fine except the following which seems to be Mac specific -- I'm testing on an Ubuntu machine:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by VWoeltjen** [comment] 2016-10-24 16:59
In answer to your question, the `master` branch is unstable and this sort of bug may occur. Tagged releases have undergone more thorough testing.

Not sure why this is occurring as #1269 should have fixed it; self-assigning to investigate.

**Comment by klyn** [comment] 2016-10-26 08:52
I managed to get **0.11.3** installed on my Mac machine, but still no chance with any of the the *0.11.x* versions on my Ubuntu machine.

If you have any hints for why I see that `Missing: mine`, then I might be able to solve it by myself. Other versions -- except *master*, have breaking exceptions, so nothing shows up at the page at all, but I rather work on the *master* branch since it doesn't have a breaking exception and those issues seems to be solved in the latest version.

**Comment by VWoeltjen** [comment] 2016-10-26 17:15
Ah, yes, a lot of the older builds were broken by changes in dependencies (for slightly more info, see #1291)

Did some debugging; I'm able to reproduce this when I have nothing persisted to browser local-storage (e.g. by starting fresh in an Incognito tab.) This got by smoke-testing because there's already a persisted version of My Items in dev environments. Believe this was introduced by #1269 (which replaced legacy handling of root-level objects, but failed to include this particular case.)

Branch `my-items-1284` includes a fix for this which restores some legacy components. I'll be filing a PR shortly after. Thanks for reporting this!

**Comment by akhenry** [comment] 2016-11-10 00:29
Testathon 11-09-2016: Verified fixed in local dev environment by running in a new incognito tab in local dev environment.

**Comment by larkin** [comment] 2016-12-01 21:17
Has come back after composition api changes, short fix on the way.

**Closed** 2016-12-01 23:41 UTC
Labels: needs investigation, regression
