### ISSUE TITLE
Static Root Plugin does not work with overlay plots

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6549] opened 2023-04-01 19:42 UTC
#### Summary

Currently the static root plugin will not load overlay plots. There appear to be two issues:
1. A key is getting corrupted somewhere, resulting in an object value for a `key` attribute instead of a string (observe the [object Object] in the screenshot below)
2. Overlay Plots are performing mutation on view initialization.

A cardinal rule in Open MCT development is that mutation should **_not_** be used to initialize view state. The reasons for this are:

a) It results in unnecessary fetches to the data store.
b) It makes it impossible to use the view with immutable objects (eg. via the Static Root Plugin).

#### Expected vs Current Behavior
The attached JSON should load correctly.

#### Steps to Reproduce
1. Clone and build [the Yamcs Quickstart project](https://github.com/yamcs/quickstart#yamcs-quickstart)
2. Clone and build [the openmct-yamcs example project](https://github.com/akhenry/openmct-yamcs#running-the-example).
3. Modify the openmct-yamcs repository to load the attached JSON using the Static Root Plugin
```
      openmct.install(openmct.plugins.StaticRootPlugin({
          namespace: 'performance-tests',
          exportUrl: './performance.json'
      }));

```
4. Run the Yamcs Quickstart project
4. Run the Open MCT-yamcs example project
5. Observe that [the attached JSON](https://github.com/nasa/openmct/files/11161814/test-display-layout.json.zip) does not load correctly via the Static Root Plugin

#### Environment
* Open MCT Version: b7a671d
* Deployment Type: yamcs-quickstart

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment] 2023-04-05 16:22
> @akhenry , I think in description, "mutation should be used to initialize view state", you mean "should NOT be".

I did indeed, thank you :)

**Comment by ozyx** [comment] 2023-04-05 22:00
The issue is (at least partly) due to the fact that the [StaticRootProvider falsely assumes that all child objects will be included in the static root JSON](https://github.com/nasa/openmct/blob/c0c383bf18632de3cc9baa3c4c12e3ad503f9d82/src/plugins/staticRootPlugin/StaticModelProvider.js#L91) and not from elsewhere (such as a telemetry dictionary).

**Comment by ozyx** [comment] 2023-04-12 16:36
Follow-up:

> 1. A key is getting corrupted somewhere, resulting in an object value for a key attribute instead of a string (observe the [object Object] in the screenshot below)

This was due to faulty StaticRootProvider remapping logic which was creating malformed identifiers for certain objects in composition (namely objects with a different namespace than the root):

![y composition Array(4)](https://user-images.githubusercontent.com/9259993/231522503-c080e686-1a83-4227-a068-d2b4c0506300.png)

> 2. Overlay Plots are performing mutation on view initialization.

Although it is true that this codepath exists, the failure is actually due to an issue with the exported JSON provided as it is missing its `configuration.series` data:

```json
    "d3950be9-20f5-4772-866a-37061a5caee0": {
      "identifier": {
        "key": "d3950be9-20f5-4772-866a-37061a5caee0",
        "namespace": ""
      },
      "type": "telemetry.plot.overlay",
      "composition": [
        {
          "key": "~myproject~Latitude",
          "namespace": "taxonomy"
        },
        {
          "key": "~myproject~Longitude",
          "namespace": "taxonomy"
        },
        {
          "key": "~myproject~Magnetometer.x",
          "namespace": "taxonomy"
        },
        {
          "key": "~myproject~Magnetometer.y",
          "namespace": "taxonomy"
        },
        {
          "key": "~myproject~Magnetometer.y",
          "namespace": "taxonomy"
        },
        {
          "key": "~myproject~Magnetometer.z",
          "namespace": "taxonomy"
        }
      ],
      "configuration": {
        "series": []
      },
      "name": "Merged Telemetry Views",
      "location": "8340c31e-27c1-4b71-8ab4-8aaafc3d06a1",
      "modified": 1678556902543,
      "modifiedBy": "guest",
      "createdBy": "guest",
      "created": 1678556902543,
      "persisted": 1678556902543
    },
```

The `SeriesCollection` initialization logic then tries to correct this by updating the plot domain object's configuration, resulting in the error. The other two Overlay Plots in the JSON provided load correctly because they have the corresponding entries in their configurations. An Overlay Plot created, saved, and freshly exported from Open MCT _does_ load correctly with StaticRoot.

**Comment by khalidadil** [comment] 2023-04-14 23:16
@akhenry I'm not sure if I should mark this as unverified, since it sounds like the problem was that the provided json had malformed plots (missing the configuration data).

**Comment by khalidadil** [comment] 2023-04-14 23:19
It sounds like we should only be testing to verify the keys are no longer corrupted on this issue. The mutation that was seen was associated with malformed json (the exported plot missing the configuration data).

**Closed** 2023-04-14 23:31 UTC
Labels: type:bug, severity:blocker, unverified

**Comment by ozyx** [comment] 2023-04-17 21:57
# Testing Instructions

1. Clone and build [the Yamcs Quickstart project](https://github.com/yamcs/quickstart#yamcs-quickstart)
2. Clone and build [the openmct-yamcs example project](https://github.com/akhenry/openmct-yamcs#running-the-example).
3. Modify the openmct-yamcs repository to load the attached JSON using the Static Root Plugin
```
      openmct.install(openmct.plugins.StaticRootPlugin({
          namespace: 'mct6549',
          exportUrl: './test-display-layout.json'
      }));
```
4. Run the Yamcs Quickstart project
4. Run the Open MCT-yamcs example project
5. Verify that the static root loads correctly, shows yamcs telemetry, and overlay plots work on mount

**Comment by akhenry** [comment] 2023-04-17 23:03
Verified fixed!
