### ISSUE TITLE
[Docs] Update documentation on how to troubleshoot CI issues

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4544] opened 2021-12-07 21:07 UTC
#### Summary
There are regularly issues with CI which may or may not match what is running locally. We should update our documentation with a FAQ or Troubleshooting steps on how to approach these problems.

##### e2e
- What to do if local server stuck ```lsof -i :8080 | grep LISTEN```

**Comment by shefalijoshi** [comment] 2022-01-20 14:48
Closing as a duplicate of #4576

**Closed by shefalijoshi** 2022-01-20 14:48 UTC
Labels: type:maintenance, Target:1.8.4
