### ISSUE TITLE
[Display Layout] Display Layout sporadically loses composition and conditional styling

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7141] opened 2023-10-12 17:59 UTC
#### Summary
Filed in VIPER Open MCT as 423.
Setup: a layout that contains two others, each of which uses conditional styling to control its visibility. Sporadically over the last two days (and only on the MMOC server?) the following has occurred:

1. Internal composition settings like position and size of an alphanumeric telemetry end point were reset, and a drawing object went completely missing.
2. The assignment of conditional styling to one or the other sub-layout and its condition set was lost multiple times.

No idea exactly when or why this is happening. This is a serious issue as a lot of people use sub-layouts and conditional styling in displays; this could be a blocking issue due to data displays missing needed elements. Filing as critical for now.

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment

* Open MCT Version:  3.0.2
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment] 2023-12-20 21:38
still critical

**Comment by unlikelyzero** [comment] 2023-12-20 21:41
This is likely fixed by multi click apply

**Comment by akhenry** [comment] 2024-03-22 21:43
Closed in VIPEROMCT-423. Unable to reproduce.

**Closed** 2024-03-22 21:43 UTC
Labels: type:bug, severity:critical
