### ISSUE TITLE
[Time conductor] Strange positioning of domain selector

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#864] opened 2016-04-27 19:07 UTC
The domain selector seems to be in a strange place all of a sudden. To reproduce, enable the conductor plugin.

Would like to resolve this for the live_demo if possible?

<img width="1280" alt="screen shot 2016-04-27 at 12 03 19" src="https://cloud.githubusercontent.com/assets/4215777/14864801/749823ca-0c70-11e6-9911-49f7f8899c3f.png">

**Comment by charlesh88** [comment] 2016-04-27 19:10
@akhenry Yoiks Shaggy! Taking a look now. Agree, we should fix this for the live demo.

**Comment by charlesh88** [comment] 2016-04-27 21:30
@akhenry 
1. Cannot duplicate in live_demo. Shrinking window size, dragging panes around etc. and can't cause it to happen. 
1. Also, what browser? Have tried both Chrome and Firefox.
1. This is showing with a folder selected, which doesn't and isn't supposed to happen in live_demo. Wha' happenin'?

**Comment by akhenry** [comment] 2016-04-27 21:56
@charlesh88 All good questions. Screen cap was taken from master, with conductor enabled, which is why you're seeing time conductor in folders. Browser is Chrome.

Looks like issue was introduced in 7a7877d7c4b7907b4f0a782b26ed613ea12e2121 for #318. If I go back to earlier commits in Master I don't see the issue any more. Because you're not seeing it at all, I suspect that it's a retina screen / break point issue similar to what we've seen in the past with mobile style rules.

**Comment by larkin** [comment] 2016-04-28 01:29
@akhenry interesting-- I am not using a retina display and haven't been able to reproduce this.  Charles is on retina and can't reproduce this.  Do you have browser zoomed in or out?  The styles I added for tablet/phone should not be applying to your screen-- that is something we have resolved already.

Looking at the changeset, I believe the exact bug must be at this specific change: https://github.com/nasa/openmct/commit/7a7877d7c4b7907b4f0a782b26ed613ea12e2121#diff-553151c1a014f4b14b6d9c5574de15b2L9  I moved an inline style to a class selector for cleanliness.  It looks like there is some selector that applies only on your device which now has higher precedence than the previous inline style.

Can you reproduce this bug, inspect the domain selector, and see what styles are applying?  I imagine there is something behind a media query that shouldn't be there-- either on the mct-control or on one of the parents.  If you don't see anything, post a screenshot of chrome inspector pane with all the style information; it will help diagnose.

For example, this is the information I'm looking for:

![screen shot 2016-04-27 at 6 27 27 pm](https://cloud.githubusercontent.com/assets/226503/14872933/e854536c-0ca5-11e6-94ae-52de43f76416.png)

**Comment by akhenry** [comment] 2016-04-28 01:52
@larkin @charlesh88 this is really weird, but I can't reproduce it now in master or in live_demo. In the interim period Chrome crashed on me (has been doing this lately) so it was restarted. Zooming and reloading does not reproduce the issue now.

I will come back to this tomorrow and see if it comes up again in the process of working on the live demo.

**Comment by larkin** [comment] 2016-04-28 16:00
@akhenry I have a suspicion that this may have been due to outdated CSS; if you had merged master into live_demo and hadn't rebuilt css, the inline style would be missing and that css necessary to position the element wouldn't have been generated.

**Comment by charlesh88** [comment] 2016-05-06 18:04
Moving this to the backlog as it can't be reproduced for now.

**Comment by akhenry** [comment] 2016-05-06 18:11
Oh, sorry, this is actually resolved. It was due to switching branches without regenerating CSS.

**Closed** 2016-05-06 18:12 UTC
