### ISSUE TITLE
[Timelines] Adding an Activity Mode to an Activity doesn't persist, but should 

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1274] opened 2016-10-21 17:17 UTC
(Migrated from issue reported by @charlesh88 in the WARP issue tracker)

Seen while running latest WARP master locally using local persistence. Filing as a blocker as this presents as an inability to view data.
1. Create an Activity Mode.
2. Edit a Timeline.
3. Turn on Resource Graphing for an Activity. It will appear as expected in the Resource Graph Legend list.
4. Add the Activity Mode to the Activity from the previous step. Click Ok in the Activity Mode dialog.
5. You may see a brief flash in the Resource Graph area on exiting the Activity Mode dialog, but then nothing will be displayed in the graph area.
6. Save the Timeline.
7. Observe that nothing continues to be rendered in the graph area, but should be.

**Comment by VWoeltjen** [comment] 2016-10-21 19:52
Editing the procedure link using the toolbar buttons has a similar result.

**Comment by VWoeltjen** [comment] 2016-10-21 19:59
`git bisect`ed; first bad commit: b0e842863d951c26ea9ce1418ec70d6f038a0ad6

...which is a squashed commit of a kerblillion other things, but basically, new API.

I'll try bisecting within there to see if I can narrow things down.

**Comment by akhenry** [comment] 2016-10-21 20:05
@VWoeltjen Thanks. From my debugging it looks almost as though there are different model object instances in play.

**Comment by larkin** [comment] 2016-10-21 20:19
New API says "different model instances are cool."  If you want to synchronize on changes you need to listen to mutation.

**Comment by akhenry** [comment] 2016-10-21 20:23
@larkin yep, but old code is assuming model instance is shared. API is now returning new instances.

**Comment by VWoeltjen** [comment] 2016-10-21 20:47
Drilling down further into that big old squash commit, `git bisect` points to a63e0533993cf263e84cfda9f92298aafe45f7a8

**Comment by akhenry** [comment] 2016-11-08 03:00
When a change is made to the timeline (eg. an activity mode being applied to an activity), the swimlanes are repopulated from scratch via composition. Composition retrieves the activity object models for the timeline from the cache, which returns a different activity object model instance (because of the LegacyObjectAPIInterceptor) to the one that was just modified.

**Comment by akhenry** [comment] 2016-11-08 03:32
Suspicion confirmed by adding a global 'mutation' event listener in the `ModelCacheService` that replaces the cached model with the mutated one, if the cache is holding a copy of it. Not sure if this is the right solution, but going to play around with it to see whether it has some

**Comment by larkin** [comment] 2016-11-09 00:28
Expect to be improved with #1316 but there might be some sync issues still with new objects, closing for verification.

**Closed by larkin** 2016-11-09 00:28 UTC
Labels: blocker, bug, unverified

**Comment by VWoeltjen** [comment] 2016-11-10 00:22
Verified fixed, testathon 20161109

**Comment by charlesh88** [comment] 2016-11-10 00:36
Testathon 11-09-2016: verified fixed.
