### ISSUE TITLE
Remove Angular code from Summary Widgets and make them non-creatable

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4588] opened 2021-12-15 22:04 UTC
#### Summary
* Replace [the legacy composition policy](https://github.com/nasa/openmct/blob/master/src/plugins/summaryWidget/plugin.js#L88) with [a new-style composition policy](https://github.com/nasa/openmct/blob/master/src/plugins/condition/plugin.js#L62).
* [Remove the summary widget view policy]( https://github.com/nasa/openmct/blob/master/src/plugins/summaryWidget/plugin.js#L93). I think it's just suppressing telemetry views like plots and tables for summary widgets, which themselves produce telemetry (the output of the conditional evaluation). I am fine if those views are available for now.
* [Remove the call to the objectService](https://github.com/nasa/openmct/blob/master/src/plugins/summaryWidget/src/SummaryWidget.js#L108) (not even sure what it's doing).
* Remove [the `creatable` property from the Summary Widget Object type](https://github.com/nasa/openmct/blob/master/src/plugins/summaryWidget/plugin.js#L20).

**Comment by michaelrogers** [comment] 2022-01-04 14:13
How to test:

Open the create menu
Ensure that `Summary Widget` is not available in the menu

**Comment by unlikelyzero** [comment] 2022-01-04 19:09
Re-opening. Does not appear in the menu.

**Comment by khalidadil** [comment] 2022-01-04 19:11
Verified Fixed in Testathon on 01/04/2022. Summary Widget is not available in the menu (which is expected behavior since it's no longer create-able).

**Closed** 2022-01-05 22:07 UTC
Labels: severity:blocker, type:maintenance, Target:1.8.3
