### ISSUE TITLE
Web Page allows Edit mode

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#524] opened 2016-01-21 21:44 UTC
<p>Edit mode is allowed for Web Page objects; would expect Edit Properties... here instead</p> <p>Think we just need to add "editable": false to its view definition</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1374
Originally created: Thu, 25 Jun 2015 17:17:46 -0700
Updated: Thu, 14 Jan 2016 17:12:08 -0800

**Comment by BogdanAlexandru** [comment] 2016-08-28 14:26
Does this still repro? I tried creating a Web Page and the only options I get for it are Edit Properties, so it seems it has been fixed in the meantime.

**Comment by akhenry** [comment] 2016-08-29 13:00
@BogdanAlexandru Agreed, I can't reproduce it either. Thanks for looking at this.

Marking as unverified to be picked up in next testathon. If it can't be reproduced there it will be closed.

**Closed** 2016-08-29 13:00 UTC
Labels: bug, unverified

**Comment by RCarvalhoNASA** [comment] 2016-08-29 21:49
Testathon 20160829 - I was testing this, and the edit mode seems to be working correctly, but it is not in fact displaying the entered web page in 'view' mode.  Isn't this what it is supposed to do?  Tried it with http://www.google.com and http://www.apple.com
Is there something I'm missing?

**Comment by BogdanAlexandru** [comment] 2016-08-29 22:02
That's true, web page opening fails. I should've reported it when I saw it today but I think I either didn't register it or completely forgot.

Opened an issue here: https://github.com/nasa/openmct/issues/1156

**Comment by charlesh88** [comment] 2016-08-29 22:11
@RCarvalhoNASA Yep, this is a known issue. Checkout my comments in #1156.
