### ISSUE TITLE
unable to remove object from composition

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4661] opened 2022-01-04 00:12 UTC
#### Summary
run master on local machine or use /latest
trying to remove and object from composition does not remove it.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. use old folder with couple of items in it (eg: Display Layout, SWG, clock etc)
2. context click on SWG under folder and select `remove`
3. click `ok` (observe selected SWG still inside folder)
3. click on Display Layout, got to  edit mode
4. try to remove SWG from elements pool (observe same result)

#### Environment
* Open MCT Version: 
 ``` Version Information
Version: 1.8.3-SNAPSHOT
Build Date: Mon Jan 03 2022 15:50:49 GMT-0800 (Pacific Standard Time)
Revision: 3a65f75d2190c464712fd4ee5c47f7255423da13
Branch: master
```
* Deployment Type: 
* OS:
* Browser:

#### Additional Information
1. caused by, Rewrite local storage (#4583) 2d64813a4fa5bfb69f16f7ab8e2753f73f232a8b
2. only unable to delete old objects
3. can delete newly created objects

**Comment by akhenry** [comment] 2022-08-08 21:19
Close to retest as potential dupe of https://github.com/nasa/openmct/issues/4915

**Comment by ozyx** [comment] 2022-08-09 20:25
Testathon 8/9/22:

still seeing an issue here:

1. Created a swg in a subfolder.
2. Created a display layout
3. Added the swg to the display layout by drag and drop
4. Removed the swg from the display layout by right-clicking the child object under the swg in the tree and selecting 'Remove'
5. **The swg is still visible in the display layout**
6. Removed the swg original object by right-click and remove
7. Successfully deleted the swg and did not appear in the folder either in the tree or in the main object view (when the folder was selected)

**Comment by jvigliotta** [comment] 2022-08-09 20:34
Not Fixed - Testathon 8/9/22

Same results as @ozyx above.

**Comment by jvigliotta** [comment] 2022-08-15 20:11
This is an odd one. I'm seeing it in a different way now:

Steps to Reproduce:

1. In a folder, create a SWG and a Display Layout
2. Drag the SWG into the Display Layout and Save and Finish Editing
3. Edit the Display Layout again and remove the SWG from the Elements Pool in the inspector (right click "remove"), Save and Finish Editing
4. Drag that same SWG back into the Display Layout and Save and Finish Editing
5.

**Comment by jvigliotta** [comment] 2022-08-15 22:05
## Testing

> Testathon 8/9/22:
> 
> still seeing an issue here:
> 
> 1. Created a swg in a subfolder.
> 2. Created a display layout
> 3. Added the swg to the display layout by drag and drop
> 4. Focus another object (other than the display layout)
> 5. Removed the swg from the display layout by right-clicking the child object under the swg in the tree and selecting 'Remove'
> 6. Focus the display layout again
> 7. **_The swg is still visible in the display layout_**
> 8. Removed the swg original object by right-click and remove
> 9. Successfully deleted the swg and did not appear in the folder either in the tree or in the main object view (when the folder was selected)

Follow these steps from @ozyx

**Closed** 2022-08-18 13:53 UTC
Labels: type:bug, severity:critical, bug:regression, unverified, Target:2.0.7, Target:2.0.8

**Comment by shefalijoshi** [comment] 2022-08-22 21:56
Verified Fixed

**Comment by khalidadil** [comment] 2022-08-22 21:57
I'm still seeing the bug when following the steps from @ozyx

**Comment by unlikelyzero** [comment] 2022-08-22 22:14
FURTHER investigation needed

**Comment by jvigliotta** [comment] 2022-08-22 22:22
Ah... I see what's going on here, the fix I had would fix if you deleted the item from the dislpay layout when NOT viewing the display layout. This is an interesting one. Since it's a linked item... do we delete it EVERYWHERE?

**Comment by khalidadil** [comment] 2022-08-22 22:33
@jvigliotta ahh, glad I posted the video! In that case, it looks like this is good.

Verified Fixed in Testathon on 08/22/22

**Comment by jvigliotta** [comment] 2022-08-22 22:50
@khalidadil Wahoooooo! Thanks man. @unlikelyzero I think we're good to go on this one.
