### ISSUE TITLE
[Vue Plots] need view policy to prevent non-plottable plugin views to display as plot

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3975] opened 2021-06-25 19:39 UTC
## Overview
Many custom views for types are being displayed in plot view when they are not plottable.

## Expected Behavior
Non-plottable plugin views should not have a plot view nor should it be the highest priority view

## Steps to Reproduce
1. See that types with only non-numerical telemetry do not have plot view available (may need to create an add a type if none available)

**Comment by akhenry** [comment] 2021-06-25 21:07
Dupe of https://github.com/nasa/openmct/issues/3977 ?

**Comment by davetsay** [comment] 2021-07-06 23:53
> Dupe of #3977 ?

I think that other issue is re: time conductor

**Closed** 2021-07-15 01:12 UTC
Labels: Target: VISTA, regression, severity:critical, type:bug
