### ISSUE TITLE
[Edit Mode] When composing objects via drag-drop, previously selected objects remain highlighted

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#771] opened 2016-03-17 22:58 UTC
20160317 testathon

This seems to occur inconsistently. Observed it with tables and with layouts, but happened more regularly in tables.

To reproduce:
1. Create a new data table
2. Drag a number of telemetry objects into the table
3. Some objects remain highlighted in the tree.

<img width="312" alt="screen shot 2016-03-17 at 15 54 31" src="https://cloud.githubusercontent.com/assets/4215777/13863718/12240e0c-ec59-11e5-9c28-06c5f27b0c33.png">

Ignore info bubble in above.

**Comment by VWoeltjen** [comment] 2016-03-18 19:18
Investigated briefly to see if this is related to new tree. I can reproduce this in v0.9.2, which predates the tree refactor.

Using Chrome developer tools, I see that the `:hover` pseudo-class is still being applied, even though the mouse is no longer hovering over these elements:

![screen shot 2016-03-18 at 12 01 54 pm](https://cloud.githubusercontent.com/assets/1685764/13888950/444e844a-ed01-11e5-9d7e-9a95db5f2419.png)

This looks like a Chrome bug, _possibly_ [this one](https://bugs.chromium.org/p/chromium/issues/detail?id=410328), although the description is a little different. There are a few SO questions linked to from there which sound more similar to our problem; the [workarounds](http://stackoverflow.com/questions/17946886/hover-sticks-to-element-on-drag-and-drop) there are to use mouse events and JavaScript to add/remove classes to behave like one would expect `:hover` to.

I'd rather not resort to that, and I think our best option is to wait for this to be fixed in Chrome. If this causes significant user confusion (I don't anticipate that it will) then we should revisit.

**Comment by akhenry** [comment] 2016-03-18 19:28
@VWoeltjen Agree, if it's a chrome bug my inclination is to let them fix it rather than using workarounds. The bug was reported  > 1 year ago though, and they don't seem to be in a hurry to fix it, so it could be a while, and it's low priority. Maybe we should report what we're seeing to the chromium team to try and revive the issue?

**Comment by charlesh88** [comment] 2016-03-21 16:26
I agree with the above. I don't think this will cause major issues, and would definitely prefer not to have cram in JS mechanics to fix this.

**Comment by VWoeltjen** [comment] 2016-03-21 16:29
> The bug was reported > 1 year ago though, and it has a low priority. They don't seem to be in a hurry to fix it, so it could be a while. Maybe we should report what we're seeing to the chromium team to try and revive the issue?

Added a [comment](https://bugs.chromium.org/p/chromium/issues/detail?id=410328#c14) indicating we believe we're observing this. (Note to self: If issue persists, should also comment with a link to a live demo once we have one available.)

**Comment by charlesh88** [comment] 2018-07-02 21:30
Appears to be fixed with later functional changes, perhaps with sub-object editing. Adding unverified and closing for testathon.

**Closed by charlesh88** 2018-07-02 21:30 UTC
Labels: bug

**Comment by dtailor90** [comment] 2018-07-02 22:44
Verified Fixed - 07/02/18
