### ISSUE TITLE
[Summary Widget] Performance issue

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1877] opened 2018-01-16 17:02 UTC
Steps to reproduce:

1- Create a sine wave generator and set the data rate to 1000 hz.  
2- Create a summary widget and add the sine wave generator created in the previous step.
3- Add a rule. Set the condition to use the "sine wave generator" telemetry and select "time" field and "is defined" comparison. 
4- Duplicate this condition 100 times.
5- Duplicate the rule at least 4 times.

Notice the app gets slowed down and becomes unresponsive and causes the browser to crash.

**Comment by akhenry** [comment] 2018-01-23 01:20
There is a PR that goes some way to addressing this - https://github.com/nasa/openmct/pull/1888

It mostly improves 'steady-state' performance of the Summary Widgets however. For a complex Summary Widget with a lot of rules and conditions, there is still a significant slow-down when you first navigate to it which will cause the browser to become unresponsive for some minutes.

I've done some investigation and I think I've found the root cause of the problem. As the complexity of the SummaryWidget's rules grow, the VM spends more and more time in garbage collection until it gets to a point where all it does is garbage collect. 

This is due, I believe, to a large number of unnecessary object and HTML node instantiations associated with the Summary Widgets editor. Even in browse mode, the entire editing UI is loaded but hidden, including all of the forms for editing Rules and Conditions. According to the performance timeline in Chrome it's spending most of its time on load in `Select.setSelected`. This is completely unnecessary in browse mode. 

The selects, and other markup elements are all loaded by the `Condition` object when it's created for each condition. This object seems to be largely UI related, and does not _appear_ to be used for the actual _evaluation_ of conditions. This is seemingly confirmed by commenting out [the line where condition objects are created](https://github.com/nasa/openmct/blob/master/src/plugins/summaryWidget/src/Rule.js#L395) and observed no ill-effect on the actual evaluation of Conditions in browse mode on the `SummaryWidget`. What I did observe was a significant improvement in performance however, with the Summary Widget loading in about a second.

So, there __is__ an opportunity for a quick fix here which significantly improves performance in browser mode, whereby Conditions and all of the other editing UI are only loaded when in edit mode. The down side of this is that complex summary widgets will still be prone to freezing the browser in edit mode. 

To address the edit mode performance we have a couple of options
1. Do not evaluate rules while editing them (it's a slight inconvenience, admittedly, but for high data rates with complex rules it might make the UI a bit more responsive while editing)
2. Only show UI elements that are visible. eg. don't show editing forms for rules and conditions that are not expanded (and they are all collapsed by default).

**Comment by larkin** [comment] 2018-01-26 18:11
Some simple improvements for this can be found in https://github.com/nasa/openmct/pull/1888, needs to be worked into a new PR to merge in master.

Baseline approach was to cache element selectors, prevent unnecessary mutation (when no changes existed), and to prevent excessive rebuilding of certain html strings (e.g. debounce description generation).  Much more work needs to be done here.

**Comment by akhenry** [comment] 2022-02-17 21:05
Closing, Summary Widgets have been replaced by Condition Widgets

**Closed by akhenry** 2022-02-17 21:05 UTC
