### ISSUE TITLE
[PreviewAction] Use API instead of importing PreviewAction.js

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#7683] opened 2024-04-11 19:27 UTC
**Is your feature request related to a problem? Please describe.**

We need to be using our own API functions when possible. A current example of where this needs to be done, is using PreviewAction.js instead of our ActionsAPI.

This is a general search for where it's being misused (ignoring it's own plugin)
https://github.com/search?q=repo%3Anasa%2Fopenmct%20import%20PreviewAction&type=code

**Describe the solution you'd like**

Replace direct usage of the PreviewAction.js class and use the ActionsAPI version.

**Describe alternatives you've considered**

The alternative is what's currently being done, we need to get away from that.

**Additional context**

Example:
Not using API
https://github.com/nasa/openmct/blob/master/src/plugins/LADTable/components/LadRow.vue#L64
https://github.com/nasa/openmct/blob/master/src/plugins/LADTable/components/LadRow.vue#L239-L273

Using the API we can remove the import and replace this line: https://github.com/nasa/openmct/blob/master/src/plugins/LADTable/components/LadRow.vue#L239

with
```js
this.previewAction = this.openmct.actions.getAction('preview');
```

**Comment by ozyx** [comment] 2024-05-01 23:58
dupe of #6426

**Closed** 2024-05-01 23:58 UTC
Labels: type:enhancement, help_wanted
