### ISSUE TITLE
[TreeView] Suggestion: auto-scroll on a new selection if the selected node is not visible

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1648] opened 2017-07-12 16:35 UTC
This is a requirement for https://github.com/nasa/openmct/pull/1340

However, I think it can be used outside of the New Folder button just as well. For example, have a deep enough hierarchy of objects, click on one near the bottom, try to create a new child within it (e.g. Folder within Folder), note that in the creation wizard even though the parent is selected in the locator, the locator is scrolled all the way to the top and the parent is not visible.

Other example: Go To Original does not auto-scroll to the original, so it's possible in a large hierarchy to have the original selected while still being out of the viewed area.

Thoughts on making this behavior happen for all TreeView use cases? It sounds like a sensible rule to me, I can't think of a case where we want to have selections happen in trees, without scrolling to the items if they're hidden.

If you agree, I'd rather create a separate PR for this due to it affecting functionality outside the New Folder button, and to not complicate the review process for the original PR. There's also some weird behavior with my current auto-scroll implementation that I'd like to check and review separately.

**Comment by charlesh88** [comment] 2017-08-25 21:45
@BogdanAlexandru I think doing in the tree does make a lot of sense, but should be done as you say as a separate issue and PR.

**Comment by VWoeltjen** [comment] 2017-08-28 16:03
Closing as a duplicate of #214, but yes, we should definitely have this! If you have a PR, I'd be more than happy to look it over. Thanks!

**Closed by VWoeltjen** 2017-08-28 16:03 UTC
