### ISSUE TITLE
When selecting timelines in new edit mode, it takes 1-2 seconds to highlight the node

### ISSUE THREAD

**Issue by Costigan** [nasa/openmct#715] opened 2016-03-03 23:28 UTC

**Comment by VWoeltjen** [comment] 2016-03-04 00:59
Discussed during triage 3/3/2016, labeling critical. Impairment of utility is significant (esp. for the important timeline-editing sprint case) but non-harmful and can be worked-around, so not a blocker for the sprint. Allocating to Gibson to address this before closing the release

**Comment by akhenry** [comment] 2016-03-07 18:07
> Testathon 03032016 running on codriver
Saw some significant delays when switching from browse to edit mode, and while editing. Delays seem to correlate to the size of the object's contents: a complex timeline like "RP15 Timeline Rev A" would take 3 to 4 seconds from click to mode switch; a similar delay was observed in selecting a timeline's row while in edit mode. Clicking to edit a simpler layout, like mshirley/Mastcam Images, had a delay of about a second.
@charlesh88 

Originally reported on ticket #627

**Comment by akhenry** [comment] 2016-03-22 00:17
The delay is caused by all of the representations in the timeline being refreshed on selection of a swimlane.

The reason for this is a little convoluted. There are a lot of steps involved, so I've skipped a few in the explanation below

1. In brief, selecting a swimlane [changes](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/representers/EditToolbar.js#L192) the `toolbarState` of the EditToolbar.
2. The above results in the selected swimlane being [updated with the state of the toolbar](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/representers/EditToolbar.js#L235). In the process, the activity's model gets [updated with its modes](https://github.com/nasa/openmct/blob/master/platform/features/timeline/src/controllers/swimlane/TimelineSwimlaneDecorator.js#L45), which uses mutation to set the value. This causes the `modified` date to be set.
3. Meanwhile, an [unusual watch](https://github.com/nasa/openmct/blob/master/platform/features/timeline/src/controllers/TimelineController.js#L106) in TimelineController is calculating the sum of the last modified dates of all the activities in the timeline. The previous step caused this date to change, triggering this watch, which repopulates all swimlanes on the screen. This triggers mctRepresentation to be called a tonne of times, etc.

**Comment by VWoeltjen** [comment] 2016-03-22 00:22
Wow, that _is_ convoluted. Nice debugging.

It would be a larger changeset, but it could be useful to replace some of those watches with mutation listeners. The watch on the modification sum is a weird hack to keep the watch count from being excessively high (but also has the effect of increasing the cost of the given watch.)

**Comment by charlesh88** [comment] 2016-03-24 22:38
Testathon 032416
Verified fixed. What a difference! Very sporty.

**Closed** 2016-03-25 00:05 UTC
Labels: critical
