### ISSUE TITLE
[Timeline] Adding nested activity causes all other changes not to persist

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#770] opened 2016-03-17 22:57 UTC
From testathon 2016-03-17 Reported by Robert, I spent some time isolating it.  Can reproduce it clearly with the following steps:

1. Create a new timeline, and save it.
2. edit your new timeline.
3. add two activities to the timeline as direct children of the timeline.
4. add a child activity to the first activity you created.
5. save the timeline.
6. note that second activity will disappear

Can do this a bunch of different ways, but whenever you add a nested activity and then save a timeline, all other newly created activities in the timeline will not persist and will disappear.

If you add a nested activity to two different parent activities, all of the new activities you added will disappear when you save the timeline.

This only occurs after the timeline has been persisted-- if you are editing a timeline and haven't yet saved it, the bug does not occur.  But if you start editing that timeline again, you can cause the error to happen.

**Comment by akhenry** [comment] 2016-03-18 00:03
This appears to be related to #678. Diagnosis below.

1. When you create the first activity, the 'AddAction' creates a new Activity object, and then as per #678 persists it immediately. It will also update the composition on its parent (the timeline). _This is not persisted immediately_
2. When you create a second activity, the same thing happens. The AddAction creates a new Activity object, and then persists it immediately. It does this by invoking EditorCapability.save(true). This has the effect of clearing the 'dirty' state in the EditableDomainObjectCache. The composition change to the timeline from adding Activity1 is now lost. The Timeline is no longer marked dirty. 
3. Hit save, the SaveAction calls EditorCapability.save() which saves everything in the cache that is marked dirty. Timeline is no longer dirty, so the compositional change from step 1. is not persisted.

**Comment by VWoeltjen** [comment] 2016-03-18 22:45
Is this a dupe of #764?

**Comment by akhenry** [comment] 2016-03-18 23:59
@VWoeltjen Yes, I believe so

**Comment by VWoeltjen** [comment] 2016-03-21 17:44
Filed #773; want to test with this more, but now see all objects persist as expected following the steps in the original issue (thanks @larkin for making this so easy to reproduce)

**Comment by VWoeltjen** [comment] 2016-04-01 18:19
Verified testathon 20160401

**Closed by VWoeltjen** 2016-04-01 18:19 UTC
Labels: bug, critical, unverified
