### ISSUE TITLE
Resource Graphing in Timeline bad axis labeling

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#909] opened 2016-05-09 21:12 UTC
Working on a timeline in the stable version of WARP (Nobile May 2016), and the numbers on the y axis of the plot don't make any sense.  See attached image.  The Battery State-of-Charge should be from 100% at the top to 0% at the bottom.  The power should be 38W at the top and -222.9W at the bottom.  Further, the number in the middle on the power plot is lower than the number at the bottom.
![badscaling](https://cloud.githubusercontent.com/assets/5769437/15128303/e0675764-15ef-11e6-9e17-e5371fb4d6b2.jpg)

**Comment by VWoeltjen** [comment] 2016-05-09 21:13
@charlesh88 - I think this may be a CSS issue? Labels look reversed (we do this intentionally in plots for desired ellipsis behavior, may be the same classes being applied here)

**Comment by VWoeltjen** [comment] 2016-05-10 18:48
Want to take here not to fix this in a manner which could cause regressions in plots (e.g. avoid changing existing styles.) Rather, timelines should just not use the styles that were intended for plots

**Comment by charlesh88** [comment] 2016-05-11 03:03
Can't work on this: getting latest on open master fails to run npm start or gulp develop.

**Comment by charlesh88** [comment] 2016-05-11 05:55
PR filed, closing.

**Closed by charlesh88** 2016-05-11 05:55 UTC
Labels: blocker

**Comment by VWoeltjen** [comment] 2016-05-11 20:53
> The power should be 38W at the top and -222.9W at the bottom.

@RCarvalhoNASA  - Quick question on this. Once the character ordering of the axis labels is fixed, the bottom of the Power graph reads -402.9W. I _believe_ this is correct, but want to double-check this with you since you were expecting a different number. I see that the lowest peak is associated with "PSR 1 AIM", which has Activity Mode "Prospecting", which in turn has a power utilization of -402.9W. No concurrent Activities have Activity Modes, so I expect to see -402.9 on the bottom of that graph. Is that right or have I missed something?

**Comment by VWoeltjen** [comment] 2016-05-12 19:49
Verified testathon 20160512

**Comment by akhenry** [comment] 2016-05-12 20:28
👍

**Comment by charlesh88** [comment] 2016-05-12 20:28
Testathon 20160512
Verified fixed, see screenshot.
<img width="1794" alt="screen shot 2016-05-12 at 1 28 53 pm" src="https://cloud.githubusercontent.com/assets/1056412/15229337/7647c2b2-1845-11e6-8199-675ff0ee3708.png">
