### ISSUE TITLE
[Fixed Position] Show info bubble for elements in view

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#569] opened 2016-01-21 22:02 UTC
<p>Show inspection popup on hover over elements in Fixed Position view, as shown in p. 34 of UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-615" title="Implement fixed position view" class="issue-link" data-issue-key="WTD-615"><del>WTD-615</del></a></p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-885
Originally created: Fri, 13 Feb 2015 16:41:25 -0800
Updated: Thu, 14 Jan 2016 16:29:34 -0800

**Comment by charlesh88** [comment] 2017-09-18 18:21
Dupe of #508

**Closed by charlesh88** 2017-09-18 18:21 UTC
