### ISSUE TITLE
createObject called twice

### ISSUE THREAD

**Issue by vinnitu** [nasa/openmct#2159] opened 2018-09-03 16:58 UTC
I implement custom persistence service and I found out that createObject is called twice for the same values, one of which is not used. Is it a bug?

**Comment by vinnitu** [comment] 2018-09-21 15:13
Hello, 

![image](https://user-images.githubusercontent.com/432168/45889519-5d86ed80-bdc9-11e8-8634-ad67eda087c3.png)
for example create hyperlink in my items - before press ok

![image](https://user-images.githubusercontent.com/432168/45889605-8c9d5f00-bdc9-11e8-901f-4c87da4c05e4.png)
after we can see two objects (4f40efcb-2a38-4cea-a0a5-98b2302dc8e5, e85750ca-adf7-407c-979a-3970e6c39886) insead of one (4f40efcb-2a38-4cea-a0a5-98b2302dc8e5)

![image](https://user-images.githubusercontent.com/432168/45889046-25cb7600-bdc8-11e8-9f9a-f82c856fef62.png)
in openmct/platform/persistence/local/src/LocalStoragePersistenceProvider.js

I have implemented own server-side storage and detect it when see serial calls of createObject() but in case of localstorage situation is the same

**Comment by akhenry** [comment] 2018-09-21 16:27
@vinnitu Thanks for the additional info! This looks like a bug to me.

@aayusharora Thanks for your input here. I'm going to mark this issue help wanted, so feel free to investigate it if you have the time. If not, let me know and one of us will pick it up.

**Comment by larkin** [comment] 2018-10-01 17:06
@akhenry @vinnitu this is a dupe of #1468 which has a candidate fix in https://github.com/nasa/openmct/pull/1471.  Due to ongoing changes to APIs it hasn't been merged yet.  We can revisit soon.

**Closed by larkin** 2018-10-01 17:06 UTC
Labels: bug, help wanted
