### ISSUE TITLE
Remove all * Listeners used by views

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3688] opened 2021-02-16 20:55 UTC
With the new Mutable DomainObject changes, we no longer need * listeners. In some cases, these listeners are causing issues since the mutable domainObject will keep itself updated.

We should remove all * Listeners that are being used to observe mutation changes on domainObjects passed into the view via the view API. Listeners may still be needed in cases where the view uses the Object API to retrieve a domainObject

**Comment by akhenry** [comment] 2021-02-25 15:58
Oh man, I knew I'd created an issue for this already but I couldn't find it when you created this. Thought I was going crazy :) This is a dupe of https://github.com/nasa/openmct/issues/3553

**Closed** 2021-02-25 15:59 UTC
Labels: bug, critical
