### ISSUE TITLE
Uncaught TypeError: this.stopObservingObjectChanges is not a function

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4073] opened 2021-08-03 18:28 UTC
#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by akhenry** [comment] 2021-08-03 21:04
Dupe of https://github.com/nasa/openmct/issues/4074

**Closed by akhenry** 2021-08-03 21:04 UTC
Labels: Target:1.7.6, severity:medium, type:bug
