### ISSUE TITLE
[mct-table] column auto-sizing not working.

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#802] opened 2016-03-30 18:29 UTC
It's not properly auto-sizing columns.

**Comment by larkin** [comment] 2016-03-30 18:31
Can't always force it to reoccur, think it has something to do with the ordering of digest cycles particularly when updateRows is called via update headers or via some other codepath.

**Comment by larkin** [comment] 2016-03-30 18:32
Seems that setting rows and headers in the same digest cycle may cause it to occur.

**Comment by larkin** [comment] 2016-03-30 18:49
I've reproduced this in branch repro-802.  Some background, I'm trying to debug code in VISTA that is using mct-table and isn't displaying data period, and haven't yet reproduced that behavior but have reproduced the sizing bug that we've seen before.

**Comment by akhenry** [comment] 2016-03-30 18:51
Hrm, interesting. Should be easy enough to stagger these so they do not happen concurrently

**Comment by akhenry** [comment] 2016-03-30 18:56
There is also another related issue here #798

**Comment by akhenry** [comment] 2016-03-30 18:58
The issue above will mean that in a realtime table some column data may get truncated if it exceeds the length of the first row + padding.

**Comment by larkin** [comment] 2016-03-30 19:06
Are you saying that the code should intentionally stagger setting rows and headers?  These activities happening concurrently shouldn't break autosizing.  Requires too much thought for the user or mct-table.

**Comment by akhenry** [comment] 2016-03-30 19:21
No, not saying it's the right solution, I don't have a good understanding of the root cause. Would not be hard to stagger them if that were the answer though.

**Comment by akhenry** [comment] 2016-03-30 19:27
Remind me again why a fixed width layout is necessary at all? It adds a bunch of complexity.

**Comment by akhenry** [comment] 2016-03-30 19:28
I assume it's around the large table optimizations

**Comment by larkin** [comment] 2016-03-30 20:44
Yes, Fixed width is also a requirement for fixed headers.  Have to balance it with performance needs and the improved UX of a table that uses screen space efficiently versus one that requires scrolling when it really should not require scrolling.

On the performance front:

Say you're rendering 80k rows of data (sine wave for 1 day).  For five columns, you get to allocate about 480,000 elements.  If you do this, the browser will autosize columns accurately.  It will also take minutes to render the table.

So then if you want to do this the smart way, you render only 100 rows and reuse the rows.  Doing this requires you to know how tall the entire table would be, which means you have to know how tall each row is.  If you fix a height on the rows, then you can't let words wrap.  Fixed width attempts to reduce wrapping, but there's no perfect calculation method that doesn't have a visible performance impact; wrapping will occasionally happen.

**Solutions?**

#798: Allowing users to see all of the text in a cell in the case that it does wrap would resolve.  My recommendation would be to use alt-text.  Alternatively, could add css on hover that sets overflow:visible and performs some kind of text wrapping / z-index bump to display full contents of highlighted cell.

This issue: Preventing the column autosizing from being sensitive to the digest cycle should be pretty easy.  I'm not sure the exact cause of the issue, but it may be that calling update headers should trigger `updateRows` if displayRows is `undefined`.

Oh hey, it might be as simple as registering your watchers the other way around. On line 70, instead of:

```javascript
$scope.$watch('headers', this.updateHeaders.bind(this));
$scope.$watch('rows', this.updateRows.bind(this));
```

have you tried 

```javascript
$scope.$watch('rows', this.updateRows.bind(this));
$scope.$watch('headers', this.updateHeaders.bind(this));
```

?

**Comment by akhenry** [comment] 2016-03-31 01:41
> Allowing users to see all of the text in a cell in the case that it does wrap would resolve

I'm not sure this will resolve it. A column in the first row might have a value of 0, and the subsequent rows might have 15+ characters. I think the only answer, if we're sticking with fixed size tables, is to dynamically resize.

**Comment by larkin** [comment] 2016-03-31 02:15
@akhenry you're correct, in that case it wouldn't help.  Something that tracks line length (e.g. using the same logic as findLargestRow) on each addRow event would allow us to dynamically resize only when the largestRow changes, which I think would be an option with reasonable performance.

In the realm of edge cases, if a column in the first row contains `llll` and then the second row contains `wwww` then our dynamic resizing wouldn't notice a difference even though there is a significant difference.  In our implementation of findLargestRow, we have traded accuracy for performance, which is a worthwhile trade.  My previous suggestion would resolve that edge case without obscuring data.

**Comment by charlesh88** [comment] 2016-04-18 22:11
Per Andrew, removed "unverified" label - this issue didn't make it into the build for today's Testathon.

**Comment by akhenry** [comment] 2016-04-25 17:55
Resolved by #822

**Closed by akhenry** 2016-04-25 17:55 UTC
Labels: bug, unverified

**Comment by akhenry** [comment] 2016-05-09 22:22
**Testing Notes**
Column values in historical tables should not be truncated, and column widths should be appropriately distributed. If this is not working, would expect to see either truncation of column values, or an even distribution of column widths.

**Comment by VWoeltjen** [comment] 2016-05-09 22:41
Testathon 20160509: Unable to test Historical Tables, but have not observed any issues with column sizing in Real-time Tables (have observed appropriate resizing in response to both incoming data and user actions, e.g. resizing the container)
