### ISSUE TITLE
[Timeline] Implement context menus

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#560] opened 2016-01-21 22:02 UTC
<p>Implement context menus in a timeline view. These are similar to existing context menus for domain objects but apply to selections instead</p> <p>See UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-846" title="[Timeline] First implementation of new timeline design" class="issue-link" data-issue-key="WTD-846"><del>WTD-846</del></a>, p. 92</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-927
Originally created: Wed, 25 Feb 2015 13:03:42 -0800
Updated: Thu, 14 Jan 2016 16:54:59 -0800

**Comment by charlesh88** [comment] 2017-09-18 18:13
Closing as a dupe of #508 and #513.

**Closed by charlesh88** 2017-09-18 18:13 UTC
Labels: fall-cleaning
