### ISSUE TITLE
[Inspection] Location section keeps rerendering

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1706] opened 2017-09-12 21:09 UTC
Steps to reproduce:

1. Expand the Inspection Area to the right
2. View a Sine Wave Generator as a Plot
3. __Observe:__ The "Location" section of the Inspection area flashes while the content keeps rerendering, about once per second

**Comment by larkin** [comment] 2017-09-16 16:39
dupe of #1696 .

**Closed by larkin** 2017-09-16 16:39 UTC
