### ISSUE TITLE
[Time List View] Time List View not sorting based on saved properties

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7103] opened 2023-10-02 18:03 UTC
#### Summary
Setting the Time List view to sort by Earliest First doesn't apply that setting to the view by default.

#### Expected vs Current Behavior
Setting the Time List view sort order should apply that setting to the view by default.

#### Steps to Reproduce

1. 
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment] 2023-11-02 16:02
Closing - unable to reproduce this.

**Closed by shefalijoshi** 2023-11-02 16:02 UTC
Labels: type:bug, severity:medium

**Comment by rukmini-bose** [comment] 2024-03-20 18:34
Can't reproduce this 3/2024

**Comment by charlesh88** [comment] 2024-03-20 21:14
Testathon 2024-03-20 cannot repro, think this has been fixed.
