### ISSUE TITLE
Persistence errors in Condition Sets when editing Condition Widgets

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4146] opened 2021-08-24 19:53 UTC
#### Summary
Seen during Science Open MCT tagup 8-24-21. Persistence errors encountered frequently (but sporadically) and by multiple users when editing Condition Widgets that use Condition Sets for styling. Users were not able to save edited properties for the Condition Widget. Users were saving sets and widgets in their own independent folders. Trying to dupe this after the session, wasn't able to replicate.
<img width="661" alt="Screen Shot 2021-08-25 at 7 34 55 AM" src="https://user-images.githubusercontent.com/12446869/130810503-c2d5768f-23b2-4218-99e1-db6230fe0e01.png">

#### Expected vs Current Behavior
No errors.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Make a Condition Set (CS) and a Condition Widget.
2. Use the CS to conditionally style the widget. Save it.
3. Edit properties for the widget, change the label and/or add a value into the URL field. Save.

#### Environment
* Open MCT Version: 1.7.7
* Deployment Type: /stable
* OS:
* Browser:

**Comment by akhenry** [comment] 2021-08-30 18:44
Once again, Condition Sets should not be mutating condition set objects unless the user has changed something.

**Comment by shefalijoshi** [comment] 2021-09-23 22:06
See #https://github.com/nasa/openmct/issues/4254

**Comment by akhenry** [comment] 2021-09-23 22:25
See VIPEROMCT-60 for detailed reproduction steps.

**Comment by akhenry** [comment] 2021-09-23 22:26
Closed #4254 as a dupe of this one. Brought reference to JIRA issue with repro steps across as comment.

**Closed** 2021-09-28 19:44 UTC
Labels: type:bug, severity:critical, unverified, Target:1.7.8

**Comment by charlesh88** [comment] 2021-09-28 23:06
Testathon 9-28-21: verified fixed.

**Comment by jvigliotta** [comment] 2021-09-28 23:07
Verified Fixed - Testathon 9/28
