### ISSUE TITLE
[Search] Search menu is dismissed when clicking a menu item

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1065] opened 2016-06-30 19:41 UTC
Observed in latest build of master running locally. When using the search filter menu, clicking a checkbox to add it to the filter immediately dismisses the menu. Instead, the menu should remain visible until the user clicks off the menu. Filing as a regression, as the correct behavior can be observed in the [live demo](https://openmct-demo.herokuapp.com/#/browse/mine/88a26104-8bd5-445d-8b57-10b567d2823d?view=layout) currently.

**Comment by akhenry** [comment] 2016-06-30 20:14
Yeah it's definitely a regression caused by #1004 which is a fix for #1000. Investigating...

**Comment by akhenry** [comment] 2016-06-30 21:50
Addressed this in #1066

**Comment by akhenry** [comment] 2016-06-30 23:16
### Note to testers

#### To verify this fix
1. Launch the search options menu by clicking on the down error next to the search box
2. Select some search options from the resulting menu. __Expected result__: The menu should not be dismissed
3. Click outside of the search options popup. __Expected result__: The menu should be dismissed

The behavior changed here affects most popups that are dismissable by clicking elsewhere on the screen. This includes
* The search menu
* The create menu
* The view switcher
* Plot mode (stacked v. overlay)
* The color picker (found in fixed view)
* Toolbar menus

These popups should be tested to ensure that they behave in a predictable way. While the popup (menu, overlay, etc.) is active, clicking elsewhere in the screen should dismiss it.

**Comment by larkin** [comment] 2016-07-18 18:25
Basic expected functionality: 
* Clicking dropdown for a menu should toggle menu on/off.  
* Selecting items from menu should hide menu & update related fields.
* Clicking anywhere outside menu should hide menu.

**Comment by charlesh88** [comment] 2016-07-18 22:07
Testathon 2016-07-18 Verified fixed

**Comment by VWoeltjen** [comment] 2016-07-18 22:28
Verified in VISTA, testathon 2016-07-18

**Comment by larkin** [comment] 2016-07-18 22:28
testathon 2016-07-18: Can say that search is fixed.  However, #888 is now broken again.  The view selector also has the same behavior (cannot toggle closed by clicking the same thing that toggled it open), which I consider broken.

Need to fix how we handle this common interaction so that we are not breaking all of our damn menus every time.  Reused code that needs to behave differently in every scenario, and now we're in this situation.

**Comment by RCarvalhoNASA** [comment] 2016-07-18 22:53
So I'm seeing a related issue with not identifying or clearing the filters that are in use, I'll file that one separately.  #1087

**Closed** 2016-07-18 23:32 UTC
Labels: bug, regression, unverified

**Comment by charlesh88** [comment] 2016-08-08 21:58
Testathon 08-08-2016: verified fixed.

**Comment by VWoeltjen** [comment] 2016-08-08 22:26
Verified in testathon 20160808

**Comment by larkin** [comment] 2016-08-08 22:27
verified in testathon 2016-08-08

**Comment by Costigan** [comment] 2016-08-08 22:52
verified in testathon 2016-08-08 (me too)

**Comment by RCarvalhoNASA** [comment] 2016-08-29 21:43
verified testathon 20160829

**Comment by charlesh88** [comment] 2016-08-29 21:53
Testathon 2016-08-29: verified fixed.

**Comment by VWoeltjen** [comment] 2016-08-29 22:41
Oh yeah, this one is _so_ verified...
