### ISSUE TITLE
[Display Layout] Adding a Drawing Object to a parent layout also adds it to the child layout

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7176] opened 2023-10-25 21:35 UTC
#### Summary

When you are editing a Display Layout that contains other Display Layouts as child elements, using the "+Add" button to add a drawing shape, line, text, or image to the main layout also adds the object to the child layout. This bug is also editing the sublayout by adding these unwanted objects. You can see this happening  by navigating to the original sublayout object, and seeing that the object has been added to it. (Shown in video). 

This can be very problematic, as this bug is making unwanted edits to layouts, whose changes persist. If users are creating personal complex displays that consist of layouts that are shared by many people and should be minimally edited, this problem can escalate pretty quickly. 

https://github.com/nasa/openmct/assets/48999852/6c951340-aa12-4bab-983c-390e223d3aa0

#### Expected vs Current Behavior

If you are in Edit mode of a Display Layout, regardless of if it contains other child Display Layouts or not, adding a drawing object should _only_ add the object to the main layout. Subobject editing should only occur if the user has clicked on the subobject in the main layout. 

#### Steps to Reproduce

1. Create/Navigate to a Display Layout. 
2. Make sure the Display Layout contains one or more child Display Layouts. 
3. Ensuring you are in Edit Mode for the parent Display Layout, add a drawing object using the "+Add" button. 
4. Observe that the object you've chosen has been added to both the parent and child layout. 
5. Save the layout, and navigate to one of the child layouts used by either using the Object Tree, or pressing the "Go to Original" button. Observe that the changes made to the child layout (an unwanted object being added) are still there. 

#### Environment

* Open MCT Version:   3.2.0
* Deployment Type:   /Testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment] 2023-10-25 23:45
Issue seems caused by [this refactor](https://github.com/nasa/openmct/pull/7057/commits/3135f7cda3cb81a584f773624f5912fac23e2c61)

**Comment by ozyx** [comment] 2023-11-02 20:26
# Testing Instructions

- Create a display layout with multiple sub layouts within it

- Add a drawing object to the parent layout and verify only one object is added to the parent
- Remove it and verify it is removed
- Add a drawing object to a child layout and verify only one object is added to the correct child
- Remove it and verify it is removed
- Repeat above with all the different drawing objects

- Add an SWG to the parent layout
- Click it and change its view to any of the other options
- Verify that the SWG changes its view correctly
- Try this with all the views
- Add an SWG to one of the child layouts and do the same

- Add 2 SWGs to the parent layout
- Switch their views to "overlay plot"
- shift + click both of them and merge them
- Verify they are merged together into one object
- Do the same for 2 SWGs in a child layout
- Delete and verify it is deleted

- Duplicate an object in the parent layout, verify it is duped
- Duplicate an object in the child layout, verify it is duped
- Repeat the same for all drawing objects, and for any sub-object view (such as plot, alphanumeric, etc)

**Closed** 2023-11-02 20:42 UTC
Labels: type:bug, severity:blocker, bug:regression, unverified

**Comment by rukmini-bose** [comment] 2023-11-13 22:59
Testathon 11/13: 
- Case 1 Verified 
- Case 2 Verified 
- Case 3 Verified 
- Case 4 Verified 
Amazing, this looks great :)
