### ISSUE TITLE
[New Plots] Editing plot objects: newly added elements don't appear in Elements pool

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1831] opened 2017-12-06 01:58 UTC
Observed during Testathon 12-05-17.

1. Create new plot, add telem elems via drag into plot area or Elements pool. 
1. Nothing is displayed in Elem pool, but elems showing in Inspector "Series Options" and data is plotted (when in time view). 
1. Expand the legend, note that items will appear in Elements pool.

Expected behavior: adding elems to a plot object adds them to the Elements pool as well.

**Comment by larkin** [comment] 2018-03-02 23:19
Dupe of #1881 and #1869 and can be closed.

**Closed by larkin** 2018-03-02 23:19 UTC
Labels: bug, critical
