### ISSUE TITLE
[User Requests] New time conductor popups should be closed by hitting ESC key

### ISSUE THREAD

**Issue by kobe1104** [nasa/openmct#3976] opened 2021-06-25 19:43 UTC
Referring to #3311 

### Testing
1. Switch to live mode by selecting 'Local Clock' at the time conductor.
2. Click on start time to open the time conductor inpouts.
Expected: The input popup should be closed when clicking ESC key.
Actual: Hitting ESC Key is not closing the input popup.

**Comment by akhenry** [comment] 2021-08-18 20:20
Dupe of https://github.com/nasa/openmct/issues/3977

**Closed by akhenry** 2021-08-18 20:20 UTC
Labels: type:bug, severity:medium
