### ISSUE TITLE
[Timeline] Splitter wiggles when zoomed out

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1141] opened 2016-08-24 17:58 UTC
When viewing a Timeline while zoomed out, sometimes the dividers between the panes of a timeline can be observed to "wiggle" a little (switching back and forth between two different pixel positions.) Guessing this has something to do with rounding and/or the synchronization of splitters on opposite panels.

Have definitely observed this for the vertical splitter, believe I've seen it for horizontal splitters too.

Reproducible at a resolution of 1366x768 with Chrome zoomed out to 67%. (Have seen it at other zoom levels as well.)

**Comment by jlaneve** [comment] 2016-08-24 22:07
Can confirm this happens in Chrome when zoomed out, but does not happen in Safari (no matter the zoom, as far as I can tell)

**Comment by TypicalFooBar** [comment] 2016-08-28 04:02
I have some information on this - I was doing some digging to try to solve this problem (I've seen the wiggle on both the vertical and horizontal splitters at different zoom levels in Chrome).

Check out this line of code: https://github.com/nasa/openmct/blob/master/platform/commonUI/general/src/directives/MCTSplitPane.js#L132

I don't exactly know what's going on here, but I found that if you hard code the `splitterSize` (instead of computing it) you get the following behaviors:

- Hard coding `splitterSize` to **9** or lower, then try viewing at different zoom levels
 - The splitters will slowly make their way to the left (for vertical splitters) or up (for horizontal splitters)
- Hard coding `splitterSize` to **11** or higher, then try viewing at different zoom levels
 - The splitters will slowly make their way to the right (for vertical splitters) or down (for horizontal splitters)
- Hard coding `splitterSize` to **10** exactly, then try viewing at different zoom levels
 - The splitters on the Timeline do not wiggle and do not move from where the user placed them.
 - The far left pane (with _My Items_ and the _Create_ button) does not work correctly while trying to move the splitter when this is hard coded to 10, but the Timeline splitters no longer wiggle at different zoom levels.

I don't understand why this behavior is happening or why hard coding the `splitterSize` to **10** seems to "fix" the issue for the splitters on the Timeline, but maybe this information can help someone else figure out what is going on with the Timeline splitters at different zoom levels.

**Comment by VWoeltjen** [comment] 2016-08-29 19:38
Thanks for debugging that, I think those notes will be helpful. I also notice is that `updateChildren` is being called extremely frequently from a timeout; that itself is a little problematic as that should only be necessary when something has changed.

**Comment by hudsonfoo** [comment] 2016-09-05 07:33
I've tested this like crazy. Thanks to @TypicalFooBar for the insights into `splitterSize`. It appears to be a bug in the browser when retrieving the `offsetWidth` of certain `absolute` positioned elements at various zoom levels. Here's a video of the `offsetWidth` of `mct-splitter` oscillating between 9 and 11: http://quick.as/JbJtxv1g. It is _not_ being set in the styles directly and the CSS attributes aren't changing either. It appears to be that the `offsetWidth` changes based on its surrounding elements instead which shouldn't happen.

Anyway, by switching the vertical bar to relative positioning and setting height to 100%, we overcome the bug and the wiggle goes away. Everything appears to work well. Here's a video of the exact conditions used above with the only change being to `_splitter.scss`: http://quick.as/eJ0CBnZw

Here's the change I made:

```diff
        >.splitter {
            cursor: col-resize;
            top: 0;
            bottom: 0;
            width: $splitterD;
+           position: relative;
+           height: 100%;
            &:after {
                left: $inset; right: $inset;
                //width: $splitterHandleD;
            }
            &.flush-right {
                width: ceil($splitterD / 2);
                &:after {
                    width: $splitterHandleD;
                    left: auto; right: 0;
                }
                &.edge-shdw {
                    @include background-image(linear-gradient(90deg, rgba(black, 0) 40%, rgba(black, 0.05) 70%, rgba(black, 0.2) 100%));
                }
            }
        }
```

**Comment by hudsonfoo** [comment] 2016-09-05 09:15
Should refactoring the updateChildren function be moved to a new issue? I agree that it's super inefficient and needs to be resolved either way. Runs every 15ms at all times. It's bound to be a performance hit as well.

**Comment by TypicalFooBar** [comment] 2016-09-05 16:34
Good find @hudsonfoo!

So as not to forget that `updateChildren()` is being called so frequently (as you and @VWoeltjen have found), I agree that another issue should be opened for it. I don't know enough about the function, though, and maybe there was a reason it's recomputing everything so often. It can't hurt to dive in and take a look.

**Comment by akhenry** [comment] 2016-09-05 17:36
> It appears to be a bug in the browser when retrieving the offsetWidth of certain absolute positioned elements at various zoom levels

Just out of interest, did you find any known issues in Chrome describing this behavior?

Unless I'm misunderstanding this issue, preventing updateChildren being called unnecessarily would both fix this issue and potentially improve performance. If that's the case I'm inclined to go with that solution? 

If calling updateChildren on a timeout is unavoidable, then a css solution to fix the visual weirdness is great, and let's create a separate issue to reduce the frequency of calls for performance reasons.

**Comment by akhenry** [comment] 2016-09-05 17:39
Also, nice debugging guys! This is awesome stuff.

**Comment by hudsonfoo** [comment] 2016-09-06 01:15
I found lots of tangential bugs like [this](https://bugs.chromium.org/p/chromium/issues/detail?id=104074)  but none that were exactly the same.

Refactoring updateChildren technically wouldn't fix the issue, it just makes it a lot less obvious since the DOM is updated less frequently.

**Comment by hudsonfoo** [comment] 2016-09-18 13:57
Saw this issue on horizontal splitter today. I didn't see it prior to this so I thought it was a non-issue. I'll need to update this ticket with a fix for that as well. Should require basically the same fix.

**Comment by akhenry** [comment] 2016-10-24 19:40
Assigning issue to me to investigate possibility of code fix here that could improve performance as well as fixing visual weirdness.

**Comment by charlesh88** [comment] 2017-09-18 20:26
Can't reproduce, closing.

**Closed by charlesh88** 2017-09-18 20:26 UTC
Labels: help wanted, trivial
