### ISSUE TITLE
Creating a custom section and page title prefixes the name with `Unnamed`

### ISSUE THREAD

**Issue by michaelrogers** [nasa/openmct#5983] opened 2022-11-14 23:33 UTC
#### Summary

When creating a new notebook, if the user adds custom section and page titles, the chosen name is prefixed with `Unnamed` + custom name.

![Screen Shot 2022-11-14 at 5 29 20 PM](https://user-images.githubusercontent.com/7417521/201789943-5df18675-4038-4b56-a5ff-da28edf5d27f.png)
![Screen Shot 2022-11-14 at 5 34 23 PM](https://user-images.githubusercontent.com/7417521/201789982-4b28f1df-0227-4ead-8cb6-68b435f58947.png)

#### Expected vs Current Behavior

A custom name should not be prefixed with the `Unnamed` prefix. It is expected that the chosen name is saved.

#### Steps to Reproduce

1. Open the create menu and start creating a new notebook
2. Give the section and/or page a custom name
3. Create the notebook
4. Observe the custom name is prefixed with `Unnamed`

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment] 2022-11-19 01:09
I think this may be correct behavior. The confusing part is the label "Section Title" and "Page Title". I think the idea is that you can override the "Section" and "Page" labels. For example, instead of "Sections" and "Pages" you may have "Folios" and "Documents".

I could be wrong. 

@charlesh88: Is this correct behavior?

**Comment by ozyx** [comment] 2023-09-11 17:08
Closing as won't fix as I'm 99.9999% certain this is intended behavior

**Closed by ozyx** 2023-09-11 17:08 UTC
Labels: type:bug, severity:trivial
