### ISSUE TITLE
y-axes for stacked plots do not line up

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4129] opened 2021-08-18 17:36 UTC
#### Summary

Space is collapsing down to the size of each y-axis value set. Different y-axis value widths cause plots to not be lined up vertically.

#### Expected vs Current Behavior

The y-axes should adjust y-axis value width so that the left-most part of all plots line up vertically.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug?

#### Steps to Reproduce

1. Create a stacked plot
2. Observe whether the y-axes line up vertically with one another
2. Adjust the plot data/type as needed so that various y-axis value widths are present. ie. 5.3 and 64.0005

#### Environment
* Open MCT Version: 1.7.6
* Deployment Type: 
* OS:
* Browser:

#### Additional Information

![image](https://user-images.githubusercontent.com/3614296/129946226-7592db20-131b-499d-9477-d8bfa462846f.png)

**Comment by shefalijoshi** [comment] 2021-09-28 21:31
Created a new PR for 1.7.8 - See #4267

**Comment by shefalijoshi** [comment] 2021-09-28 21:34
This is a duplicate of #3955

**Closed** 2021-09-29 19:50 UTC
Labels: type:bug, severity:critical, regression, visual, Target:1.7.8
