### ISSUE TITLE
[Tree] Add favorite objects feature

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1798] opened 2017-11-07 19:50 UTC
User could select an object as a favorite, and then it would appear under a separate 'favorites' root at the top of navigation pane. 

Alternatively, a 'recently viewed' root could achieve a similar thing without explicitly marking objects as favorites.

@charlesh88 Thoughts on design? In its simplest implementation, 'Add to Favourites' could simply be a context action.

**Comment by VWoeltjen** [comment] 2018-01-11 00:06
Duplicate of #578; migrating to comment there

**Closed by VWoeltjen** 2018-01-11 00:06 UTC
