### ISSUE TITLE
[DisplayLayout] Object removal from object tree doesn't consistently remove object from Display Layout in main window

### ISSUE THREAD

**Issue by johnriedel** [nasa/openmct#3117] opened 2020-06-25 16:51 UTC
Overview to reproduce error:
1. Add an item to display layout, then "Save and Finish Editing"
2. Select the child item in the object tree so that it's active in the main window
3. Right-click and remove object. Notice it was removed from object tree but not display layout.

Detailed steps to reproduce error:
1. Add a display layout to "My Items" folder
2. In Display Layout main window, click "Save and Finish Editing"
3. Add a "State Generator" object to the Display Layout in the object tree
4. Select the Dispay Layout in the object tree so it's active in the main window
5. Note that you can see the State Generator in the display layout in the upper left corner of the main window
6. Select the State Generator in the object tree so it's active in the main window
7. Right-click the State Generator and select Remove from the drop-down menu
8. Note that the State Generator is removed from the object tree, which is expected
9. Select the Display Layout in the object tree so it's active in the main window
10. Note that the State Generator was not removed from the display layout in the main window, which is unexpected behavior.

Expected behavior: When the state generator is removed from the display layout in the object tree, it should also be removed from the display layout in the main window.

Actual behavior: When the state generator is removed from the display layout in the object tree, it's not removed from the display layout in the main window.

(Ubuntu 16.04 - Firefox 77.0.1 64-bit, Chrome Version 70.0.3538.102 64-bit)

**Comment by ozyx** [comment] 2022-11-02 18:44
This is still an issue. The object is currently removed from the displayLayout's composition correctly, but stays behind in its configuration (`configuration.items`).

**Comment by ozyx** [comment] 2022-11-02 20:30
regression caused by changes in #5827

**Comment by ozyx** [comment] 2022-11-10 17:26
# Testing Notes

## Deleting an object in a layout using the RemoveAction while viewing another object

1. Create an object (any)
2. Create a Display Layout
3. Drag the object into the display layout and save it
5. Navigate to the parent object
6. Right-click on the child object of the display layout in the object tree and remove it
8. Verify that the object has been removed in the display layout and in the tree
9. navigate away and back, verify it's still removed

Repeat the steps above for Flexible Layout

## Deleting an object in a layout using the RemoveAction while viewing the layout
1. Same steps as above, but remove the child object while viewing the layout itself

Repeat the steps above for Flexible Layout

**Comment by khalidadil** [comment] 2022-11-14 23:10
Verified Fixed in Testathon on 11/14/22

**Comment by ozyx** [comment] 2023-07-24 17:05
> # Testing Notes
> ## Deleting an object in a layout using the RemoveAction while viewing another object
> 1. Create an object (any)
> 2. Create a Display Layout
> 3. Drag the object into the display layout and save it
> 4. Navigate to the parent object
> 5. Right-click on the child object of the display layout in the object tree and remove it
> 6. Verify that the object has been removed in the display layout and in the tree
> 7. navigate away and back, verify it's still removed
> 
> Repeat the steps above for Flexible Layout
> 
> ## Deleting an object in a layout using the RemoveAction while viewing the layout
> 1. Same steps as above, but remove the child object while viewing the layout itself
> 
> Repeat the steps above for Flexible Layout

This regressed with the Vue 3 upgrade. Re-opening, this should be verified with the instructions above

**Closed** 2023-07-24 20:37 UTC
Labels: type:bug, severity:critical, bug:regression

**Comment by shefalijoshi** [comment] 2023-07-24 21:21
Verified Fixed. Tried removing items from the tree, from the main display layout and from the elements pool.

**Comment by rukmini-bose** [comment] 2023-07-24 21:21
Verified Testathon 7/24/2023

**Comment by rukmini-bose** [comment] 2023-07-24 21:28
Testathon 6/24/2023: Removing child objects from a layout does not update the tree.
