### ISSUE TITLE
[Plot] Display out-of-bounds glow

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#621] opened 2016-01-21 23:27 UTC
<p>Display "glow" (as shown in UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-868" title="UI for setting plot bounds in a plot view" class="issue-link" data-issue-key="WTD-868"><del>WTD-868</del></a>) when there is out-of-bounds data for the visible plot area. Description of states when this glow should apply are given in those UI docs.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1135
Originally created: Sun, 26 Apr 2015 10:50:09 -0700
Updated: Thu, 21 Jan 2016 15:05:29 -0800

**Comment by VWoeltjen** [comment] 2016-01-21 23:27
Migrated comment, from @VWoeltjen:
<blockquote>
<p>Other concerns to consider in the implementation of this feature:</p>

<ul class="alternate" type="square">
	<li>In the future, will likely want to be able to configure plot axes such that max is on bottom instead of top, or that data values like across the x axis instead of the y axis</li>
	<li>Conditions which determine visibility need to behave sensibly during user-initiated pan and zoom operations</li>
	<li>Implementation needs to take into account performance concerns (e.g. should not be a bottleneck when a lot of plots with a lot of data are onscreen)</li>
</ul>

</blockquote>

**Comment by charlesh88** [comment] 2017-09-18 18:48
Closing as dupe of #526

**Closed by charlesh88** 2017-09-18 18:48 UTC
Labels: plotting
